// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Rule that specifies conditions when a certain infoType's finding details
/// should be adjusted.
public struct AdjustmentRule: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Likelihood adjustment to apply to the infoType.
  public var likelihoodAdjustment: CustomInfoType.DetectionRule.LikelihoodAdjustment? = nil

  /// Condition under which the adjustment rule is applied.
  public var conditions: OneOf_Conditions? = nil

  /// Initialize a new instance of `AdjustmentRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AdjustmentRule().with { $0.adjustByMatchingInfoTypes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case adjustByMatchingInfoTypes = "adjustByMatchingInfoTypes"
    case adjustByImageFindings = "adjustByImageFindings"
    case likelihoodAdjustment = "likelihoodAdjustment"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.likelihoodAdjustment = try container.decodeIfPresent(
      CustomInfoType.DetectionRule.LikelihoodAdjustment.self, forKey: .likelihoodAdjustment)

    var conditions: OneOf_Conditions? = nil
    let conditionsCheckAndSet = {
      if conditions != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'conditions'"))
      }
      conditions = $0
    }
    if let adjustByMatchingInfoTypes = try container.decodeIfPresent(
      AdjustByMatchingInfoTypes?.self, forKey: .adjustByMatchingInfoTypes)
    {
      try conditionsCheckAndSet(.adjustByMatchingInfoTypes(adjustByMatchingInfoTypes))
    }
    if let adjustByImageFindings = try container.decodeIfPresent(
      AdjustByImageFindings?.self, forKey: .adjustByImageFindings)
    {
      try conditionsCheckAndSet(.adjustByImageFindings(adjustByImageFindings))
    }
    self.conditions = conditions
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.likelihoodAdjustment, forKey: .likelihoodAdjustment)

    if let choice = self.conditions {
      switch choice {
      case .adjustByMatchingInfoTypes(let value):
        try container.encode(value, forKey: .adjustByMatchingInfoTypes)
      case .adjustByImageFindings(let value):
        try container.encode(value, forKey: .adjustByImageFindings)
      }
    }
  }

  /// Condition under which the adjustment rule is applied.
  public enum OneOf_Conditions: Codable, Equatable, Sendable {
    /// Set of infoTypes for which findings would affect this rule.
    indirect case adjustByMatchingInfoTypes(AdjustByMatchingInfoTypes?)
    /// AdjustmentRule condition for image findings.
    indirect case adjustByImageFindings(AdjustByImageFindings?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.AdjustmentRule"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
