// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Options defining BigQuery table and row identifiers.
public struct BigQueryOptions: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Complete BigQuery table reference.
  public var tableReference: BigQueryTable? = nil

  /// Table fields that may uniquely identify a row within the table. When
  /// `actions.saveFindings.outputConfig.table` is specified, the values of
  /// columns specified here are available in the output table under
  /// `location.content_locations.record_location.record_key.id_values`. Nested
  /// fields such as `person.birthdate.year` are allowed.
  public var identifyingFields: [FieldId] = []

  /// Max number of rows to scan. If the table has more rows than this value, the
  /// rest of the rows are omitted. If not set, or if set to 0, all rows will be
  /// scanned. Only one of rows_limit and rows_limit_percent can be specified.
  /// Cannot be used in conjunction with TimespanConfig.
  public var rowsLimit: Swift.Int64 = Swift.Int64()

  /// Max percentage of rows to scan. The rest are omitted. The number of rows
  /// scanned is rounded down. Must be between 0 and 100, inclusively. Both 0 and
  /// 100 means no limit. Defaults to 0. Only one of rows_limit and
  /// rows_limit_percent can be specified. Cannot be used in conjunction with
  /// TimespanConfig.
  ///
  /// Caution: A [known
  /// issue](https://cloud.google.com/sensitive-data-protection/docs/known-issues#bq-sampling)
  /// is causing the `rowsLimitPercent` field to behave unexpectedly. We
  /// recommend using `rowsLimit` instead.
  public var rowsLimitPercent: Swift.Int32 = Swift.Int32()

  /// How to sample the data.
  public var sampleMethod: BigQueryOptions.SampleMethod = BigQueryOptions.SampleMethod()

  /// References to fields excluded from scanning. This allows you to skip
  /// inspection of entire columns which you know have no findings.
  /// When inspecting a table, we recommend that you inspect all columns.
  /// Otherwise, findings might be affected because hints from excluded columns
  /// will not be used.
  public var excludedFields: [FieldId] = []

  /// Limit scanning only to these fields.
  /// When inspecting a table, we recommend that you inspect all columns.
  /// Otherwise, findings might be affected because hints from excluded columns
  /// will not be used.
  public var includedFields: [FieldId] = []

  /// Initialize a new instance of `BigQueryOptions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BigQueryOptions().with { $0.tableReference = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// How to sample rows if not all rows are scanned. Meaningful only when used
  /// in conjunction with either rows_limit or rows_limit_percent. If not
  /// specified, rows are scanned in the order BigQuery reads them.
  public enum SampleMethod: Codable, Equatable, Sendable {
    /// No sampling.
    case unspecified
    /// Scan groups of rows in the order BigQuery provides (default). Multiple
    /// groups of rows may be scanned in parallel, so results may not appear in
    /// the same order the rows are read.
    case top
    /// Randomly pick groups of rows to scan.
    case randomStart
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .top: return 1
      case .randomStart: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SAMPLE_METHOD_UNSPECIFIED"
      case .top: return "TOP"
      case .randomStart: return "RANDOM_START"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SampleMethod/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SAMPLE_METHOD_UNSPECIFIED": self = .unspecified
      case "TOP": self = .top
      case "RANDOM_START": self = .randomStart
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SampleMethod/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .top
      case 2: self = .randomStart
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .top: return try container.encode(1)
      case .randomStart: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.BigQueryOptions"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
