// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Target used to match against for discovery with BigQuery tables
public struct BigQueryDiscoveryTarget: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The tables the discovery cadence applies to. The first target
  /// with a matching filter will be the one to apply to a table.
  public var filter: DiscoveryBigQueryFilter? = nil

  /// In addition to matching the filter, these conditions must be true
  /// before a profile is generated.
  public var conditions: DiscoveryBigQueryConditions? = nil

  /// The generation rule includes the logic on how frequently
  /// to update the data profiles. If not specified, discovery will re-run and
  /// update no more than once a month if new columns appear in the table.
  public var frequency: OneOf_Frequency? = nil

  /// Initialize a new instance of `BigQueryDiscoveryTarget`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BigQueryDiscoveryTarget().with { $0.filter = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case filter = "filter"
    case conditions = "conditions"
    case cadence = "cadence"
    case disabled = "disabled"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.filter = try container.decodeIfPresent(DiscoveryBigQueryFilter.self, forKey: .filter)
    self.conditions = try container.decodeIfPresent(
      DiscoveryBigQueryConditions.self, forKey: .conditions)

    var frequency: OneOf_Frequency? = nil
    let frequencyCheckAndSet = {
      if frequency != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'frequency'"))
      }
      frequency = $0
    }
    if let cadence = try container.decodeIfPresent(
      DiscoveryGenerationCadence?.self, forKey: .cadence)
    {
      try frequencyCheckAndSet(.cadence(cadence))
    }
    if let disabled = try container.decodeIfPresent(Disabled?.self, forKey: .disabled) {
      try frequencyCheckAndSet(.disabled(disabled))
    }
    self.frequency = frequency
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.filter, forKey: .filter)
    try container.encode(self.conditions, forKey: .conditions)

    if let choice = self.frequency {
      switch choice {
      case .cadence(let value):
        try container.encode(value, forKey: .cadence)
      case .disabled(let value):
        try container.encode(value, forKey: .disabled)
      }
    }
  }

  /// The generation rule includes the logic on how frequently
  /// to update the data profiles. If not specified, discovery will re-run and
  /// update no more than once a month if new columns appear in the table.
  public enum OneOf_Frequency: Codable, Equatable, Sendable {
    /// How often and when to update profiles. New tables that match both the
    /// filter and conditions are scanned as quickly as possible depending on
    /// system capacity.
    indirect case cadence(DiscoveryGenerationCadence?)
    /// Tables that match this filter will not have profiles created.
    indirect case disabled(Disabled?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.BigQueryDiscoveryTarget"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
