// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A policy to apply to content based on its inspection findings.
public struct ContentPolicy: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. Resource name of the policy.
  public var name: Swift.String = Swift.String()

  /// Output only. The creation timestamp of a contentPolicy; output-only field.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The last update timestamp of a contentPolicy; output-only
  /// field.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. Display name (max 63 chars)
  public var displayName: Swift.String = Swift.String()

  /// Optional. InspectConfig to use to produce findings.
  public var inspectConfig: InspectConfig? = nil

  /// Required. Policies to apply, based on the findings returned by inspection.
  /// The first rule to match applies.
  public var rules: [ContentPolicy.PolicyRule] = []

  /// Optional. Action to take if the content is an unsupported file type.
  public var unsupportedFileType: ContentPolicy.PolicyAction? = nil

  /// Optional. Action to take if the content is a supported file type but is too
  /// large to be scanned.
  public var inputTooLarge: ContentPolicy.PolicyAction? = nil

  /// Optional. Action to take if the content is a supported file type and size
  /// but fails to be scanned, for example because the file is encrypted or
  /// corrupted.
  public var failedToScanSupportedFileType: ContentPolicy.PolicyAction? = nil

  /// Action to take if the content is scanned and no rules match.
  /// Defaults to returning an ALLOW verdict if not set.
  public var defaultAction: ContentPolicy.PolicyAction? = nil

  /// Optional. Log the actions taken by the content policy to external systems.
  public var loggingConfigs: [ContentPolicy.LoggingConfig] = []

  /// Output only. A stream of errors encountered when the policy was applied.
  /// Output only field. Will return the last 100 errors. Whenever the policy is
  /// modified this list will be cleared.
  public var errors: [Error] = []

  /// Initialize a new instance of `ContentPolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ContentPolicy().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A possible action to take when applying a content policy.
  public struct PolicyAction: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    public var action: OneOf_Action? = nil

    /// Initialize a new instance of `PolicyAction`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PolicyAction().with { $0.returnVerdict = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case returnVerdict = "returnVerdict"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var action: OneOf_Action? = nil
      let actionCheckAndSet = {
        if action != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'action'"))
        }
        action = $0
      }
      if let returnVerdict = try container.decodeIfPresent(
        ContentPolicyVerdict.self, forKey: .returnVerdict)
      {
        try actionCheckAndSet(.returnVerdict(returnVerdict))
      }
      self.action = action
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.action {
        switch choice {
        case .returnVerdict(let value):
          try container.encode(value, forKey: .returnVerdict)
        }
      }
    }

    public enum OneOf_Action: Codable, Equatable, Sendable {
      /// Optional. If set, the verdict will be returned to the user.
      case returnVerdict(ContentPolicyVerdict)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.ContentPolicy.PolicyAction"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// A single policy rule. The first rule to match from the list above controls
  /// the result.
  public struct PolicyRule: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. Conditions that must match for this rule to apply.
    /// All conditions must match (`AND`). For `OR` conditions, use multiple
    /// rules.
    public var conditions: [ContentPolicy.PolicyRule.PolicyCondition] = []

    /// Required. Action to take if this rule applies.
    public var action: ContentPolicy.PolicyAction? = nil

    /// Initialize a new instance of `PolicyRule`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PolicyRule().with { $0.conditions = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// A condition that must match for this rule to apply.
    public struct PolicyCondition: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// A condition.
      public var condition: OneOf_Condition? = nil

      /// Initialize a new instance of `PolicyCondition`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = PolicyCondition().with { $0.infoTypeCondition = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private enum CodingKeys: Swift.String, CodingKey {
        case infoTypeCondition = "infoTypeCondition"
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        var condition: OneOf_Condition? = nil
        let conditionCheckAndSet = {
          if condition != nil {
            throw DecodingError.dataCorrupted(
              DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Multiple values set for oneof 'condition'"))
          }
          condition = $0
        }
        if let infoTypeCondition = try container.decodeIfPresent(
          ContentPolicy.PolicyRule.PolicyCondition.InfoTypeCondition?.self,
          forKey: .infoTypeCondition)
        {
          try conditionCheckAndSet(.infoTypeCondition(infoTypeCondition))
        }
        self.condition = condition
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        if let choice = self.condition {
          switch choice {
          case .infoTypeCondition(let value):
            try container.encode(value, forKey: .infoTypeCondition)
          }
        }
      }

      /// A info type based condition.
      public struct InfoTypeCondition: Codable, Equatable, GoogleCloudWKT._AnyPackable,
        Sendable
      {
        /// Optional. The minimum total number of findings of all matching info
        /// types required for this condition to evaluate to true. Defaults to 1
        /// if unset.
        public var minCount: Swift.Int64 = Swift.Int64()

        /// A condition based on info types.
        public var infoTypeCondition: OneOf_InfoTypeCondition? = nil

        /// Initialize a new instance of `InfoTypeCondition`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = InfoTypeCondition().with { $0.minCount = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        private enum CodingKeys: Swift.String, CodingKey {
          case minCount = "minCount"
          case infoTypes = "infoTypes"
          case anyInfoType = "anyInfoType"
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.container(keyedBy: CodingKeys.self)
          self.minCount = try container.decode(Swift.Int64.self, forKey: .minCount)

          var infoTypeCondition: OneOf_InfoTypeCondition? = nil
          let infoTypeConditionCheckAndSet = {
            if infoTypeCondition != nil {
              throw DecodingError.dataCorrupted(
                DecodingError.Context(
                  codingPath: decoder.codingPath,
                  debugDescription: "Multiple values set for oneof 'infoTypeCondition'"))
            }
            infoTypeCondition = $0
          }
          if let infoTypes = try container.decodeIfPresent(
            ContentPolicy.PolicyRule.PolicyCondition.InfoTypeCondition.InfoTypes?.self,
            forKey: .infoTypes)
          {
            try infoTypeConditionCheckAndSet(.infoTypes(infoTypes))
          }
          if let anyInfoType = try container.decodeIfPresent(
            GoogleCloudWKT.Empty?.self, forKey: .anyInfoType)
          {
            try infoTypeConditionCheckAndSet(.anyInfoType(anyInfoType))
          }
          self.infoTypeCondition = infoTypeCondition
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.container(keyedBy: CodingKeys.self)
          try container.encode(self.minCount, forKey: .minCount)

          if let choice = self.infoTypeCondition {
            switch choice {
            case .infoTypes(let value):
              try container.encode(value, forKey: .infoTypes)
            case .anyInfoType(let value):
              try container.encode(value, forKey: .anyInfoType)
            }
          }
        }

        /// Info types to match.
        public struct InfoTypes: Codable, Equatable, GoogleCloudWKT._AnyPackable,
          Sendable
        {
          /// Required. A list of info types to match.
          public var infoTypeNames: [Swift.String] = []

          /// Initialize a new instance of `InfoTypes`.
          public init() {}

          /// Use `config` to return a new instance of this object, with some fields updated.
          ///
          /// Commonly used to initialize the value, for example:
          ///
          /// ```
          /// let value = InfoTypes().with { $0.infoTypeNames = ... }
          /// ```
          public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
            var copy = self
            try config(&copy)
            return copy
          }

          public static var _anyTypeUrl: Swift.String {
            return
              "type.googleapis.com/google.privacy.dlp.v2.ContentPolicy.PolicyRule.PolicyCondition.InfoTypeCondition.InfoTypes"
          }
          public init(fromAny any: GoogleCloudWKT.`Any`) throws {
            self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
          }
          public func _pack() throws -> GoogleCloudWKT.Struct {
            return try GoogleCloudWKT._slowAnySerialize(message: self)
          }
        }

        /// A condition based on info types.
        public enum OneOf_InfoTypeCondition: Codable, Equatable, Sendable {
          /// match any of these info types.
          indirect case infoTypes(
            ContentPolicy.PolicyRule.PolicyCondition.InfoTypeCondition.InfoTypes?)
          /// match any info types.
          indirect case anyInfoType(GoogleCloudWKT.Empty?)
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.privacy.dlp.v2.ContentPolicy.PolicyRule.PolicyCondition.InfoTypeCondition"
        }
        public init(fromAny any: GoogleCloudWKT.`Any`) throws {
          self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWKT.Struct {
          return try GoogleCloudWKT._slowAnySerialize(message: self)
        }
      }

      /// A condition.
      public enum OneOf_Condition: Codable, Equatable, Sendable {
        /// A condition based on info types.
        indirect case infoTypeCondition(ContentPolicy.PolicyRule.PolicyCondition.InfoTypeCondition?)
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.privacy.dlp.v2.ContentPolicy.PolicyRule.PolicyCondition"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.ContentPolicy.PolicyRule"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// A single logging configuration.
  public struct LoggingConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The destination for the action logs.
    public var destination: OneOf_Destination? = nil

    /// Initialize a new instance of `LoggingConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LoggingConfig().with { $0.logToBigQuery = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case logToBigQuery = "logToBigQuery"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var destination: OneOf_Destination? = nil
      let destinationCheckAndSet = {
        if destination != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'destination'"))
        }
        destination = $0
      }
      if let logToBigQuery = try container.decodeIfPresent(
        ContentPolicy.LoggingConfig.LogToBigQuery?.self, forKey: .logToBigQuery)
      {
        try destinationCheckAndSet(.logToBigQuery(logToBigQuery))
      }
      self.destination = destination
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.destination {
        switch choice {
        case .logToBigQuery(let value):
          try container.encode(value, forKey: .logToBigQuery)
        }
      }
    }

    /// Configuration for logging content policy actions to BigQuery.
    public struct LogToBigQuery: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Required. The ID of the project containing the BigQuery table to write
      /// to.
      public var projectId: Swift.String = Swift.String()

      /// Required. The ID of the dataset containing the BigQuery table to write
      /// to.
      public var datasetId: Swift.String = Swift.String()

      /// Required. The ID of the BigQuery table to write to.
      public var tableId: Swift.String = Swift.String()

      /// Initialize a new instance of `LogToBigQuery`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = LogToBigQuery().with { $0.projectId = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.privacy.dlp.v2.ContentPolicy.LoggingConfig.LogToBigQuery"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    /// The destination for the action logs.
    public enum OneOf_Destination: Codable, Equatable, Sendable {
      /// Optional. Log the actions taken to a BigQuery table.
      indirect case logToBigQuery(ContentPolicy.LoggingConfig.LogToBigQuery?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.ContentPolicy.LoggingConfig"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.ContentPolicy"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
