// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Precise location of the finding within a document, record, image, or metadata
/// container.
public struct ContentLocation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Name of the container where the finding is located.
  /// The top level name is the source file name or table name. Names of some
  /// common storage containers are formatted as follows:
  ///
  /// * BigQuery tables:  `{project_id}:{dataset_id}.{table_id}`
  /// * Cloud Storage files: `gs://{bucket}/{path}`
  /// * Datastore namespace: {namespace}
  ///
  /// Nested names could be absent if the embedded object has no string
  /// identifier (for example, an image contained within a document).
  public var containerName: Swift.String = Swift.String()

  /// Finding container modification timestamp, if applicable. For Cloud Storage,
  /// this field contains the last file modification timestamp. For a BigQuery
  /// table, this field contains the last_modified_time property. For Datastore,
  /// this field isn't populated.
  public var containerTimestamp: GoogleCloudWkt.Timestamp? = nil

  /// Finding container version, if available
  /// ("generation" for Cloud Storage).
  public var containerVersion: Swift.String = Swift.String()

  /// Type of the container within the file with location of the finding.
  public var location: OneOf_Location? = nil

  /// Initialize a new instance of `ContentLocation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ContentLocation().with { $0.containerName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case containerName = "containerName"
    case recordLocation = "recordLocation"
    case imageLocation = "imageLocation"
    case documentLocation = "documentLocation"
    case metadataLocation = "metadataLocation"
    case conversationLocation = "conversationLocation"
    case batchContentLocation = "batchContentLocation"
    case containerTimestamp = "containerTimestamp"
    case containerVersion = "containerVersion"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.containerName = try container.decode(Swift.String.self, forKey: .containerName)
    self.containerTimestamp = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .containerTimestamp)
    self.containerVersion = try container.decode(Swift.String.self, forKey: .containerVersion)

    var location: OneOf_Location? = nil
    let locationCheckAndSet = {
      if location != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'location'"))
      }
      location = $0
    }
    if let recordLocation = try container.decodeIfPresent(
      RecordLocation?.self, forKey: .recordLocation)
    {
      try locationCheckAndSet(.recordLocation(recordLocation))
    }
    if let imageLocation = try container.decodeIfPresent(
      ImageLocation?.self, forKey: .imageLocation)
    {
      try locationCheckAndSet(.imageLocation(imageLocation))
    }
    if let documentLocation = try container.decodeIfPresent(
      DocumentLocation?.self, forKey: .documentLocation)
    {
      try locationCheckAndSet(.documentLocation(documentLocation))
    }
    if let metadataLocation = try container.decodeIfPresent(
      MetadataLocation?.self, forKey: .metadataLocation)
    {
      try locationCheckAndSet(.metadataLocation(metadataLocation))
    }
    if let conversationLocation = try container.decodeIfPresent(
      ConversationLocation?.self, forKey: .conversationLocation)
    {
      try locationCheckAndSet(.conversationLocation(conversationLocation))
    }
    if let batchContentLocation = try container.decodeIfPresent(
      BatchContentLocation?.self, forKey: .batchContentLocation)
    {
      try locationCheckAndSet(.batchContentLocation(batchContentLocation))
    }
    self.location = location
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.containerName, forKey: .containerName)
    try container.encode(self.containerTimestamp, forKey: .containerTimestamp)
    try container.encode(self.containerVersion, forKey: .containerVersion)

    if let choice = self.location {
      switch choice {
      case .recordLocation(let value):
        try container.encode(value, forKey: .recordLocation)
      case .imageLocation(let value):
        try container.encode(value, forKey: .imageLocation)
      case .documentLocation(let value):
        try container.encode(value, forKey: .documentLocation)
      case .metadataLocation(let value):
        try container.encode(value, forKey: .metadataLocation)
      case .conversationLocation(let value):
        try container.encode(value, forKey: .conversationLocation)
      case .batchContentLocation(let value):
        try container.encode(value, forKey: .batchContentLocation)
      }
    }
  }

  /// Type of the container within the file with location of the finding.
  public enum OneOf_Location: Codable, Equatable, Sendable {
    /// Location within a row or record of a database table.
    indirect case recordLocation(RecordLocation?)
    /// Location within an image's pixels.
    indirect case imageLocation(ImageLocation?)
    /// Location data for document files.
    indirect case documentLocation(DocumentLocation?)
    /// Location within the metadata for inspected content.
    indirect case metadataLocation(MetadataLocation?)
    /// Location within a conversation.
    indirect case conversationLocation(ConversationLocation?)
    /// Location within a batch of content.
    indirect case batchContentLocation(BatchContentLocation?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.ContentLocation"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
