// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for CreateContentPolicy.
public struct CreateContentPolicyRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Parent resource name.
  ///
  /// The format of this value varies depending on the scope of the request
  /// (project):
  ///
  /// + Projects scope:
  ///   `projects/{project_id}/locations/{location_id}`
  public var parent: Swift.String = Swift.String()

  /// Required. The content_policy resource.
  public var contentPolicy: ContentPolicy? = nil

  /// Optional. The content policy ID can contain uppercase and lowercase
  /// letters, numbers, and hyphens; that is, it must match the regular
  /// expression:
  ///   `[a-zA-Z\d-_]+`.
  /// The maximum length is 100 characters. If empty, the system will generate
  /// a random id.
  public var contentPolicyId: Swift.String = Swift.String()

  /// Initialize a new instance of `CreateContentPolicyRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateContentPolicyRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.CreateContentPolicyRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
