// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for CreateDiscoveryConfig.
public struct CreateDiscoveryConfigRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Parent resource name.
  ///
  /// The format of this value varies depending on the scope of the request
  /// (project or organization):
  ///
  /// + Projects scope:
  ///   `projects/{project_id}/locations/{location_id}`
  /// + Organizations scope:
  ///   `organizations/{org_id}/locations/{location_id}`
  ///
  /// The following example `parent` string specifies a parent project with the
  /// identifier `example-project`, and specifies the `europe-west3` location
  /// for processing data:
  ///
  ///     parent=projects/example-project/locations/europe-west3
  public var parent: Swift.String = Swift.String()

  /// Required. The DiscoveryConfig to create.
  public var discoveryConfig: DiscoveryConfig? = nil

  /// The config ID can contain uppercase and lowercase letters,
  /// numbers, and hyphens; that is, it must match the regular
  /// expression: `[a-zA-Z\d-_]+`. The maximum length is 100
  /// characters. Can be empty to allow the system to generate one.
  public var configId: Swift.String = Swift.String()

  /// Initialize a new instance of `CreateDiscoveryConfigRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateDiscoveryConfigRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.CreateDiscoveryConfigRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
