// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Custom information type provided by the user. Used to find domain-specific
/// sensitive information configurable to the data in question.
public struct CustomInfoType: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// CustomInfoType can either be a new infoType, or an extension of built-in
  /// infoType, when the name matches one of existing infoTypes and that infoType
  /// is specified in `InspectContent.info_types` field. Specifying the latter
  /// adds findings to the one detected by the system. If built-in info type is
  /// not specified in `InspectContent.info_types` list then the name is treated
  /// as a custom info type.
  public var infoType: InfoType? = nil

  /// Likelihood to return for this CustomInfoType. This base value can be
  /// altered by a detection rule if the finding meets the criteria specified by
  /// the rule. Defaults to `VERY_LIKELY` if not specified.
  public var likelihood: Likelihood = Likelihood()

  /// Set of detection rules to apply to all findings of this CustomInfoType.
  /// Rules are applied in the order that they are specified. Only supported
  /// for the `dictionary`, `regex`, and `stored_type` CustomInfoTypes.
  public var detectionRules: [CustomInfoType.DetectionRule] = []

  /// If set to EXCLUSION_TYPE_EXCLUDE this infoType will not cause a finding
  /// to be returned. It still can be used for rules matching. Only supported
  /// for the `dictionary`, `regex`, and `stored_type` CustomInfoTypes.
  public var exclusionType: CustomInfoType.ExclusionType = CustomInfoType.ExclusionType()

  /// Sensitivity for this CustomInfoType. If this CustomInfoType extends an
  /// existing InfoType, the sensitivity here will take precedence over that of
  /// the original InfoType. If unset for a CustomInfoType, it will default to
  /// HIGH.
  /// This only applies to data profiling.
  public var sensitivityScore: SensitivityScore? = nil

  /// Type of custom detector.
  public var type: OneOf_Type? = nil

  /// Initialize a new instance of `CustomInfoType`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CustomInfoType().with { $0.infoType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case infoType = "infoType"
    case likelihood = "likelihood"
    case dictionary = "dictionary"
    case regex = "regex"
    case surrogateType = "surrogateType"
    case storedType = "storedType"
    case metadataKeyValueExpression = "metadataKeyValueExpression"
    case detectionRules = "detectionRules"
    case exclusionType = "exclusionType"
    case sensitivityScore = "sensitivityScore"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.infoType = try container.decodeIfPresent(InfoType.self, forKey: .infoType)
    self.likelihood = try container.decode(Likelihood.self, forKey: .likelihood)
    self.detectionRules = try container.decode(
      [CustomInfoType.DetectionRule].self, forKey: .detectionRules)
    self.exclusionType = try container.decode(
      CustomInfoType.ExclusionType.self, forKey: .exclusionType)
    self.sensitivityScore = try container.decodeIfPresent(
      SensitivityScore.self, forKey: .sensitivityScore)

    var type: OneOf_Type? = nil
    let typeCheckAndSet = {
      if type != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'type'"
          ))
      }
      type = $0
    }
    if let dictionary = try container.decodeIfPresent(
      CustomInfoType.Dictionary?.self, forKey: .dictionary)
    {
      try typeCheckAndSet(.dictionary(dictionary))
    }
    if let regex = try container.decodeIfPresent(CustomInfoType.Regex?.self, forKey: .regex) {
      try typeCheckAndSet(.regex(regex))
    }
    if let surrogateType = try container.decodeIfPresent(
      CustomInfoType.SurrogateType?.self, forKey: .surrogateType)
    {
      try typeCheckAndSet(.surrogateType(surrogateType))
    }
    if let storedType = try container.decodeIfPresent(StoredType?.self, forKey: .storedType) {
      try typeCheckAndSet(.storedType(storedType))
    }
    if let metadataKeyValueExpression = try container.decodeIfPresent(
      CustomInfoType.MetadataKeyValueExpression?.self, forKey: .metadataKeyValueExpression)
    {
      try typeCheckAndSet(.metadataKeyValueExpression(metadataKeyValueExpression))
    }
    self.type = type
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.infoType, forKey: .infoType)
    try container.encode(self.likelihood, forKey: .likelihood)
    try container.encode(self.detectionRules, forKey: .detectionRules)
    try container.encode(self.exclusionType, forKey: .exclusionType)
    try container.encode(self.sensitivityScore, forKey: .sensitivityScore)

    if let choice = self.type {
      switch choice {
      case .dictionary(let value):
        try container.encode(value, forKey: .dictionary)
      case .regex(let value):
        try container.encode(value, forKey: .regex)
      case .surrogateType(let value):
        try container.encode(value, forKey: .surrogateType)
      case .storedType(let value):
        try container.encode(value, forKey: .storedType)
      case .metadataKeyValueExpression(let value):
        try container.encode(value, forKey: .metadataKeyValueExpression)
      }
    }
  }

  /// Custom information type based on a dictionary of words or phrases. This can
  /// be used to match sensitive information specific to the data, such as a list
  /// of employee IDs or job titles.
  ///
  /// Dictionary words are case-insensitive and all characters other than letters
  /// and digits in the unicode [Basic Multilingual
  /// Plane](https://en.wikipedia.org/wiki/Plane_%28Unicode%29#Basic_Multilingual_Plane)
  /// will be replaced with whitespace when scanning for matches, so the
  /// dictionary phrase "Sam Johnson" will match all three phrases "sam johnson",
  /// "Sam, Johnson", and "Sam (Johnson)". Additionally, the characters
  /// surrounding any match must be of a different type than the adjacent
  /// characters within the word, so letters must be next to non-letters and
  /// digits next to non-digits. For example, the dictionary word "jen" will
  /// match the first three letters of the text "jen123" but will return no
  /// matches for "jennifer".
  ///
  /// Dictionary words containing a large number of characters that are not
  /// letters or digits may result in unexpected findings because such characters
  /// are treated as whitespace. The
  /// [limits](https://cloud.google.com/sensitive-data-protection/limits) page
  /// contains details about the size limits of dictionaries. For dictionaries
  /// that do not fit within these constraints, consider using
  /// `LargeCustomDictionaryConfig` in the `StoredInfoType` API.
  public struct Dictionary: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The potential places the data can be read from.
    public var source: OneOf_Source? = nil

    /// Initialize a new instance of `Dictionary`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Dictionary().with { $0.wordList = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case wordList = "wordList"
      case cloudStoragePath = "cloudStoragePath"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var source: OneOf_Source? = nil
      let sourceCheckAndSet = {
        if source != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'source'"))
        }
        source = $0
      }
      if let wordList = try container.decodeIfPresent(
        CustomInfoType.Dictionary.WordList?.self, forKey: .wordList)
      {
        try sourceCheckAndSet(.wordList(wordList))
      }
      if let cloudStoragePath = try container.decodeIfPresent(
        CloudStoragePath?.self, forKey: .cloudStoragePath)
      {
        try sourceCheckAndSet(.cloudStoragePath(cloudStoragePath))
      }
      self.source = source
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.source {
        switch choice {
        case .wordList(let value):
          try container.encode(value, forKey: .wordList)
        case .cloudStoragePath(let value):
          try container.encode(value, forKey: .cloudStoragePath)
        }
      }
    }

    /// Message defining a list of words or phrases to search for in the data.
    public struct WordList: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Words or phrases defining the dictionary. The dictionary must contain
      /// at least one phrase and every phrase must contain at least 2 characters
      /// that are letters or digits. [required]
      public var words: [Swift.String] = []

      /// Initialize a new instance of `WordList`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = WordList().with { $0.words = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.privacy.dlp.v2.CustomInfoType.Dictionary.WordList"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    /// The potential places the data can be read from.
    public enum OneOf_Source: Codable, Equatable, Sendable {
      /// List of words or phrases to search for.
      indirect case wordList(CustomInfoType.Dictionary.WordList?)
      /// Newline-delimited file of words in Cloud Storage. Only a single file
      /// is accepted.
      indirect case cloudStoragePath(CloudStoragePath?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.CustomInfoType.Dictionary"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Message defining a custom regular expression.
  public struct Regex: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Pattern defining the regular expression. Its syntax
    /// (https://github.com/google/re2/wiki/Syntax) can be found under the
    /// google/re2 repository on GitHub.
    public var pattern: Swift.String = Swift.String()

    /// The index of the submatch to extract as findings. When not
    /// specified, the entire match is returned. No more than 3 may be included.
    public var groupIndexes: [Swift.Int32] = []

    /// Initialize a new instance of `Regex`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Regex().with { $0.pattern = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.CustomInfoType.Regex"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Message for detecting output from deidentification transformations
  /// such as
  /// [`CryptoReplaceFfxFpeConfig`](https://cloud.google.com/sensitive-data-protection/docs/reference/rest/v2/organizations.deidentifyTemplates#cryptoreplaceffxfpeconfig).
  /// These types of transformations are
  /// those that perform pseudonymization, thereby producing a "surrogate" as
  /// output. This should be used in conjunction with a field on the
  /// transformation such as `surrogate_info_type`. This CustomInfoType does
  /// not support the use of `detection_rules`.
  public struct SurrogateType: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `SurrogateType`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SurrogateType().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.CustomInfoType.SurrogateType"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration for a custom infoType that detects key-value pairs in the
  /// metadata matching the specified regular expressions.
  public struct MetadataKeyValueExpression: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The regular expression for the key. Key should be
    /// non-empty.
    public var keyRegex: Swift.String = Swift.String()

    /// The regular expression for the value. Value should be non-empty.
    public var valueRegex: Swift.String = Swift.String()

    /// Initialize a new instance of `MetadataKeyValueExpression`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MetadataKeyValueExpression().with { $0.keyRegex = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.CustomInfoType.MetadataKeyValueExpression"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Deprecated; use `InspectionRuleSet` instead. Rule for modifying a
  /// `CustomInfoType` to alter behavior under certain circumstances, depending
  /// on the specific details of the rule. Not supported for the `surrogate_type`
  /// custom infoType.
  public struct DetectionRule: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Type of hotword rule.
    public var type: OneOf_Type? = nil

    /// Initialize a new instance of `DetectionRule`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DetectionRule().with { $0.hotwordRule = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case hotwordRule = "hotwordRule"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var type: OneOf_Type? = nil
      let typeCheckAndSet = {
        if type != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'type'"))
        }
        type = $0
      }
      if let hotwordRule = try container.decodeIfPresent(
        CustomInfoType.DetectionRule.HotwordRule?.self, forKey: .hotwordRule)
      {
        try typeCheckAndSet(.hotwordRule(hotwordRule))
      }
      self.type = type
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.type {
        switch choice {
        case .hotwordRule(let value):
          try container.encode(value, forKey: .hotwordRule)
        }
      }
    }

    /// Message for specifying a window around a finding to apply a detection
    /// rule.
    public struct Proximity: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Number of characters before the finding to consider. For tabular data,
      /// if you want to modify the likelihood of an entire column of findngs,
      /// set this to 1. For more information, see
      /// [Hotword example: Set the match likelihood of a table column]
      /// (https://cloud.google.com/sensitive-data-protection/docs/creating-custom-infotypes-likelihood#match-column-values).
      public var windowBefore: Swift.Int32 = Swift.Int32()

      /// Number of characters after the finding to consider.
      public var windowAfter: Swift.Int32 = Swift.Int32()

      /// Initialize a new instance of `Proximity`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Proximity().with { $0.windowBefore = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.privacy.dlp.v2.CustomInfoType.DetectionRule.Proximity"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    /// Message for specifying an adjustment to the likelihood of a finding as
    /// part of a detection rule.
    public struct LikelihoodAdjustment: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// How the likelihood will be modified.
      public var adjustment: OneOf_Adjustment? = nil

      /// Initialize a new instance of `LikelihoodAdjustment`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = LikelihoodAdjustment().with { $0.fixedLikelihood = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private enum CodingKeys: Swift.String, CodingKey {
        case fixedLikelihood = "fixedLikelihood"
        case relativeLikelihood = "relativeLikelihood"
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        var adjustment: OneOf_Adjustment? = nil
        let adjustmentCheckAndSet = {
          if adjustment != nil {
            throw DecodingError.dataCorrupted(
              DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Multiple values set for oneof 'adjustment'"))
          }
          adjustment = $0
        }
        if let fixedLikelihood = try container.decodeIfPresent(
          Likelihood.self, forKey: .fixedLikelihood)
        {
          try adjustmentCheckAndSet(.fixedLikelihood(fixedLikelihood))
        }
        if let relativeLikelihood = try container.decodeIfPresent(
          Swift.Int32.self, forKey: .relativeLikelihood)
        {
          try adjustmentCheckAndSet(.relativeLikelihood(relativeLikelihood))
        }
        self.adjustment = adjustment
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        if let choice = self.adjustment {
          switch choice {
          case .fixedLikelihood(let value):
            try container.encode(value, forKey: .fixedLikelihood)
          case .relativeLikelihood(let value):
            try container.encode(value, forKey: .relativeLikelihood)
          }
        }
      }

      /// How the likelihood will be modified.
      public enum OneOf_Adjustment: Codable, Equatable, Sendable {
        /// Set the likelihood of a finding to a fixed value.
        case fixedLikelihood(Likelihood)
        /// Increase or decrease the likelihood by the specified number of
        /// levels. For example, if a finding would be `POSSIBLE` without the
        /// detection rule and `relative_likelihood` is 1, then it is upgraded to
        /// `LIKELY`, while a value of -1 would downgrade it to `UNLIKELY`.
        /// Likelihood may never drop below `VERY_UNLIKELY` or exceed
        /// `VERY_LIKELY`, so applying an adjustment of 1 followed by an
        /// adjustment of -1 when base likelihood is `VERY_LIKELY` will result in
        /// a final likelihood of `LIKELY`.
        case relativeLikelihood(Swift.Int32)
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.privacy.dlp.v2.CustomInfoType.DetectionRule.LikelihoodAdjustment"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    /// The rule that adjusts the likelihood of findings within a certain
    /// proximity of hotwords.
    public struct HotwordRule: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Regular expression pattern defining what qualifies as a hotword.
      public var hotwordRegex: CustomInfoType.Regex? = nil

      /// Range of characters within which the entire hotword must reside.
      /// The total length of the window cannot exceed 1000 characters.
      /// The finding itself will be included in the window, so that hotwords can
      /// be used to match substrings of the finding itself. Suppose you
      /// want Cloud DLP to promote the likelihood of the phone number
      /// regex "\(\d{3}\) \d{3}-\d{4}" if the area code is known to be the
      /// area code of a company's office. In this case, use the hotword regex
      /// "\(xxx\)", where "xxx" is the area code in question.
      ///
      /// For tabular data, if you want to modify the likelihood of an entire
      /// column of findngs, see
      /// [Hotword example: Set the match likelihood of a table column]
      /// (https://cloud.google.com/sensitive-data-protection/docs/creating-custom-infotypes-likelihood#match-column-values).
      public var proximity: CustomInfoType.DetectionRule.Proximity? = nil

      /// Likelihood adjustment to apply to all matching findings.
      public var likelihoodAdjustment: CustomInfoType.DetectionRule.LikelihoodAdjustment? = nil

      /// Initialize a new instance of `HotwordRule`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = HotwordRule().with { $0.hotwordRegex = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.privacy.dlp.v2.CustomInfoType.DetectionRule.HotwordRule"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    /// Type of hotword rule.
    public enum OneOf_Type: Codable, Equatable, Sendable {
      /// Hotword-based detection rule.
      indirect case hotwordRule(CustomInfoType.DetectionRule.HotwordRule?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.CustomInfoType.DetectionRule"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Type of exclusion rule.
  public enum ExclusionType: Codable, Equatable, Sendable {
    /// A finding of this custom info type will not be excluded from results.
    case unspecified
    /// A finding of this custom info type will be excluded from final results,
    /// but can still affect rule execution.
    case exclude
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .exclude: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "EXCLUSION_TYPE_UNSPECIFIED"
      case .exclude: return "EXCLUSION_TYPE_EXCLUDE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ExclusionType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "EXCLUSION_TYPE_UNSPECIFIED": self = .unspecified
      case "EXCLUSION_TYPE_EXCLUDE": self = .exclude
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ExclusionType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .exclude
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .exclude: return try container.encode(1)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Type of custom detector.
  public enum OneOf_Type: Codable, Equatable, Sendable {
    /// A list of phrases to detect as a CustomInfoType.
    indirect case dictionary(CustomInfoType.Dictionary?)
    /// Regular expression based CustomInfoType.
    indirect case regex(CustomInfoType.Regex?)
    /// Message for detecting output from deidentification transformations that
    /// support reversing.
    indirect case surrogateType(CustomInfoType.SurrogateType?)
    /// Loads an existing `StoredInfoType` resource.
    indirect case storedType(StoredType?)
    /// Key-value pair to detect in the metadata.
    indirect case metadataKeyValueExpression(CustomInfoType.MetadataKeyValueExpression?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.CustomInfoType"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
