// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A task to execute when a data profile has been generated.
public struct DataProfileAction: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Type of action to execute when a profile is generated.
  public var action: OneOf_Action? = nil

  /// Initialize a new instance of `DataProfileAction`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataProfileAction().with { $0.exportData = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case exportData = "exportData"
    case pubSubNotification = "pubSubNotification"
    case publishToChronicle = "publishToChronicle"
    case publishToScc = "publishToScc"
    case tagResources = "tagResources"
    case publishToDataplexCatalog = "publishToDataplexCatalog"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var action: OneOf_Action? = nil
    let actionCheckAndSet = {
      if action != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'action'"))
      }
      action = $0
    }
    if let exportData = try container.decodeIfPresent(
      DataProfileAction.Export?.self, forKey: .exportData)
    {
      try actionCheckAndSet(.exportData(exportData))
    }
    if let pubSubNotification = try container.decodeIfPresent(
      DataProfileAction.PubSubNotification?.self, forKey: .pubSubNotification)
    {
      try actionCheckAndSet(.pubSubNotification(pubSubNotification))
    }
    if let publishToChronicle = try container.decodeIfPresent(
      DataProfileAction.PublishToChronicle?.self, forKey: .publishToChronicle)
    {
      try actionCheckAndSet(.publishToChronicle(publishToChronicle))
    }
    if let publishToScc = try container.decodeIfPresent(
      DataProfileAction.PublishToSecurityCommandCenter?.self, forKey: .publishToScc)
    {
      try actionCheckAndSet(.publishToScc(publishToScc))
    }
    if let tagResources = try container.decodeIfPresent(
      DataProfileAction.TagResources?.self, forKey: .tagResources)
    {
      try actionCheckAndSet(.tagResources(tagResources))
    }
    if let publishToDataplexCatalog = try container.decodeIfPresent(
      DataProfileAction.PublishToDataplexCatalog?.self, forKey: .publishToDataplexCatalog)
    {
      try actionCheckAndSet(.publishToDataplexCatalog(publishToDataplexCatalog))
    }
    self.action = action
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.action {
      switch choice {
      case .exportData(let value):
        try container.encode(value, forKey: .exportData)
      case .pubSubNotification(let value):
        try container.encode(value, forKey: .pubSubNotification)
      case .publishToChronicle(let value):
        try container.encode(value, forKey: .publishToChronicle)
      case .publishToScc(let value):
        try container.encode(value, forKey: .publishToScc)
      case .tagResources(let value):
        try container.encode(value, forKey: .tagResources)
      case .publishToDataplexCatalog(let value):
        try container.encode(value, forKey: .publishToDataplexCatalog)
      }
    }
  }

  /// If set, the detailed data profiles will be persisted to the location
  /// of your choice whenever updated.
  public struct Export: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Store all profiles to BigQuery.
    ///
    /// * The system will create a new dataset and table for you if none are
    ///   are provided. The dataset will be named
    ///   `sensitive_data_protection_discovery` and table will be named
    ///   `discovery_profiles`. This table will be placed in the same project as
    ///   the container project running the scan. After the first profile is
    ///   generated and the dataset and table are created, the discovery scan
    ///   configuration will be updated with the dataset and table names.
    /// * See [Analyze data profiles stored in
    /// BigQuery](https://cloud.google.com/sensitive-data-protection/docs/analyze-data-profiles).
    /// * See [Sample queries for your BigQuery
    /// table](https://cloud.google.com/sensitive-data-protection/docs/analyze-data-profiles#sample_sql_queries).
    /// *  Data is inserted using [streaming
    ///    insert](https://cloud.google.com/blog/products/bigquery/life-of-a-bigquery-streaming-insert)
    ///    and so data may be in the buffer for a period of time after the
    ///    profile has finished.
    ///  * The Pub/Sub notification is sent before the streaming buffer is
    ///    guaranteed to be written, so data may not be instantly
    ///    visible to queries by the time your topic receives the Pub/Sub
    ///    notification.
    ///  * The best practice is to use the same table for an entire organization
    ///    so that you can take advantage of the [provided Data Studio
    ///    reports](https://cloud.google.com/sensitive-data-protection/docs/analyze-data-profiles#use_a_premade_report).
    ///    If you use VPC Service Controls to define security perimeters, then
    ///    you must use a separate table for each boundary.
    public var profileTable: BigQueryTable? = nil

    /// Store sample [data profile
    /// findings][google.privacy.dlp.v2.DataProfileFinding] in an existing table
    /// or a new table in an existing dataset. Each regeneration will result in
    /// new rows in BigQuery. Data is inserted using [streaming
    /// insert](https://cloud.google.com/blog/products/bigquery/life-of-a-bigquery-streaming-insert)
    /// and so data may be in the buffer for a period of time after the profile
    /// has finished.
    ///
    /// [google.privacy.dlp.v2.DataProfileFinding]: <doc:DataProfileFinding>
    public var sampleFindingsTable: BigQueryTable? = nil

    /// Initialize a new instance of `Export`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Export().with { $0.profileTable = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.DataProfileAction.Export"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Send a Pub/Sub message into the given Pub/Sub topic to connect other
  /// systems to data profile generation. The message payload data will
  /// be the byte serialization of `DataProfilePubSubMessage`.
  public struct PubSubNotification: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Cloud Pub/Sub topic to send notifications to.
    /// Format is projects/{project}/topics/{topic}.
    public var topic: Swift.String = Swift.String()

    /// The type of event that triggers a Pub/Sub. At most one
    /// `PubSubNotification` per EventType is permitted.
    public var event: DataProfileAction.EventType = DataProfileAction.EventType()

    /// Conditions (e.g., data risk or sensitivity level) for triggering a
    /// Pub/Sub.
    public var pubsubCondition: DataProfilePubSubCondition? = nil

    /// How much data to include in the Pub/Sub message. If the user wishes to
    /// limit the size of the message, they can use resource_name and fetch the
    /// profile fields they wish to. Per table profile (not per column).
    public var detailOfMessage: DataProfileAction.PubSubNotification.DetailLevel = DataProfileAction
      .PubSubNotification.DetailLevel()

    /// Initialize a new instance of `PubSubNotification`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PubSubNotification().with { $0.topic = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// The levels of detail that can be included in the Pub/Sub message.
    public enum DetailLevel: Codable, Equatable, Sendable {
      /// Unused.
      case unspecified
      /// The full table data profile.
      case tableProfile
      /// The name of the profiled resource.
      case resourceName
      /// The full file store data profile.
      case fileStoreProfile
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .tableProfile: return 1
        case .resourceName: return 2
        case .fileStoreProfile: return 3
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "DETAIL_LEVEL_UNSPECIFIED"
        case .tableProfile: return "TABLE_PROFILE"
        case .resourceName: return "RESOURCE_NAME"
        case .fileStoreProfile: return "FILE_STORE_PROFILE"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DetailLevel/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "DETAIL_LEVEL_UNSPECIFIED": self = .unspecified
        case "TABLE_PROFILE": self = .tableProfile
        case "RESOURCE_NAME": self = .resourceName
        case "FILE_STORE_PROFILE": self = .fileStoreProfile
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DetailLevel/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .tableProfile
        case 2: self = .resourceName
        case 3: self = .fileStoreProfile
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .tableProfile: return try container.encode(1)
        case .resourceName: return try container.encode(2)
        case .fileStoreProfile: return try container.encode(3)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.DataProfileAction.PubSubNotification"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Message expressing intention to publish to Google Security Operations.
  public struct PublishToChronicle: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `PublishToChronicle`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PublishToChronicle().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.DataProfileAction.PublishToChronicle"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// If set, a summary finding will be created or updated in Security Command
  /// Center for each profile.
  public struct PublishToSecurityCommandCenter: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `PublishToSecurityCommandCenter`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PublishToSecurityCommandCenter().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.privacy.dlp.v2.DataProfileAction.PublishToSecurityCommandCenter"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Create Dataplex Universal Catalog aspects for profiled resources with the
  /// aspect type Sensitive Data Protection Profile. To learn more about aspects,
  /// see https://cloud.google.com/sensitive-data-protection/docs/add-aspects.
  public struct PublishToDataplexCatalog: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Whether creating a Dataplex Universal Catalog aspect for a profiled
    /// resource should lower the risk of the profile for that resource. This
    /// also lowers the data risk of resources at the lower levels of the
    /// resource hierarchy. For example, reducing the data risk of a table data
    /// profile also reduces the data risk of the constituent column data
    /// profiles.
    public var lowerDataRiskToLow: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `PublishToDataplexCatalog`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PublishToDataplexCatalog().with { $0.lowerDataRiskToLow = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.DataProfileAction.PublishToDataplexCatalog"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// If set, attaches the [tags]
  /// (https://cloud.google.com/resource-manager/docs/tags/tags-overview)
  /// provided to profiled resources. Tags support [access
  /// control](https://cloud.google.com/iam/docs/tags-access-control). You can
  /// conditionally grant or deny access to a resource based on whether the
  /// resource has a specific tag.
  public struct TagResources: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The tags to associate with different conditions.
    public var tagConditions: [DataProfileAction.TagResources.TagCondition] = []

    /// The profile generations for which the tag should be attached to
    /// resources. If you attach a tag to only new profiles, then if the
    /// sensitivity score of a profile subsequently changes, its tag doesn't
    /// change. By default, this field includes only new profiles. To include
    /// both new and updated profiles for tagging, this field should explicitly
    /// include both `PROFILE_GENERATION_NEW` and `PROFILE_GENERATION_UPDATE`.
    public var profileGenerationsToTag: [ProfileGeneration] = []

    /// Whether applying a tag to a resource should lower the risk of the profile
    /// for that resource. For example, in conjunction with an [IAM deny
    /// policy](https://cloud.google.com/iam/docs/deny-overview), you can deny
    /// all principals a permission if a tag value is present, mitigating the
    /// risk of the resource. This also lowers the data risk of resources at the
    /// lower levels of the resource hierarchy. For example, reducing the data
    /// risk of a table data profile also reduces the data risk of the
    /// constituent column data profiles.
    public var lowerDataRiskToLow: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `TagResources`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TagResources().with { $0.tagConditions = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// The tag to attach to profiles matching the condition. At most one
    /// `TagCondition` can be specified per sensitivity level.
    public struct TagCondition: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// The tag value to attach to resources.
      public var tag: DataProfileAction.TagResources.TagValue? = nil

      /// The type of condition on which attaching the tag will be predicated.
      public var type: OneOf_Type? = nil

      /// Initialize a new instance of `TagCondition`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = TagCondition().with { $0.tag = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private enum CodingKeys: Swift.String, CodingKey {
        case tag = "tag"
        case sensitivityScore = "sensitivityScore"
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.tag = try container.decodeIfPresent(
          DataProfileAction.TagResources.TagValue.self, forKey: .tag)

        var type: OneOf_Type? = nil
        let typeCheckAndSet = {
          if type != nil {
            throw DecodingError.dataCorrupted(
              DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Multiple values set for oneof 'type'"))
          }
          type = $0
        }
        if let sensitivityScore = try container.decodeIfPresent(
          SensitivityScore?.self, forKey: .sensitivityScore)
        {
          try typeCheckAndSet(.sensitivityScore(sensitivityScore))
        }
        self.type = type
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.tag, forKey: .tag)

        if let choice = self.type {
          switch choice {
          case .sensitivityScore(let value):
            try container.encode(value, forKey: .sensitivityScore)
          }
        }
      }

      /// The type of condition on which attaching the tag will be predicated.
      public enum OneOf_Type: Codable, Equatable, Sendable {
        /// Conditions attaching the tag to a resource on its profile having this
        /// sensitivity score.
        indirect case sensitivityScore(SensitivityScore?)
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.privacy.dlp.v2.DataProfileAction.TagResources.TagCondition"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// A value of a tag.
    public struct TagValue: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// The format of the tag value.
      public var format: OneOf_Format? = nil

      /// Initialize a new instance of `TagValue`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = TagValue().with { $0.namespacedValue = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private enum CodingKeys: Swift.String, CodingKey {
        case namespacedValue = "namespacedValue"
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)

        var format: OneOf_Format? = nil
        let formatCheckAndSet = {
          if format != nil {
            throw DecodingError.dataCorrupted(
              DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Multiple values set for oneof 'format'"))
          }
          format = $0
        }
        if let namespacedValue = try container.decodeIfPresent(
          Swift.String.self, forKey: .namespacedValue)
        {
          try formatCheckAndSet(.namespacedValue(namespacedValue))
        }
        self.format = format
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)

        if let choice = self.format {
          switch choice {
          case .namespacedValue(let value):
            try container.encode(value, forKey: .namespacedValue)
          }
        }
      }

      /// The format of the tag value.
      public enum OneOf_Format: Codable, Equatable, Sendable {
        /// The namespaced name for the tag value to attach to resources. Must be
        /// in the format `{parent_id}/{tag_key_short_name}/{short_name}`, for
        /// example, "123456/environment/prod" for an organization parent, or
        /// "my-project/environment/prod" for a project parent.
        case namespacedValue(Swift.String)
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.privacy.dlp.v2.DataProfileAction.TagResources.TagValue"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.DataProfileAction.TagResources"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Types of event that can trigger an action.
  public enum EventType: Codable, Equatable, Sendable {
    /// Unused.
    case unspecified
    /// New profile (not a re-profile).
    case newProfile
    /// One of the following profile metrics changed: Data risk score,
    /// Sensitivity score, Resource visibility, Encryption type, Predicted
    /// infoTypes, Other infoTypes
    case changedProfile
    /// Table data risk score or sensitivity score increased.
    case scoreIncreased
    /// A user (non-internal) error occurred.
    case errorChanged
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .newProfile: return 1
      case .changedProfile: return 2
      case .scoreIncreased: return 3
      case .errorChanged: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "EVENT_TYPE_UNSPECIFIED"
      case .newProfile: return "NEW_PROFILE"
      case .changedProfile: return "CHANGED_PROFILE"
      case .scoreIncreased: return "SCORE_INCREASED"
      case .errorChanged: return "ERROR_CHANGED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EventType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "EVENT_TYPE_UNSPECIFIED": self = .unspecified
      case "NEW_PROFILE": self = .newProfile
      case "CHANGED_PROFILE": self = .changedProfile
      case "SCORE_INCREASED": self = .scoreIncreased
      case "ERROR_CHANGED": self = .errorChanged
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EventType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .newProfile
      case 2: self = .changedProfile
      case 3: self = .scoreIncreased
      case 4: self = .errorChanged
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .newProfile: return try container.encode(1)
      case .changedProfile: return try container.encode(2)
      case .scoreIncreased: return try container.encode(3)
      case .errorChanged: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Type of action to execute when a profile is generated.
  public enum OneOf_Action: Codable, Equatable, Sendable {
    /// Export data profiles into a provided location.
    indirect case exportData(DataProfileAction.Export?)
    /// Publish a message into the Pub/Sub topic.
    indirect case pubSubNotification(DataProfileAction.PubSubNotification?)
    /// Publishes generated data profiles to Google Security Operations.
    /// For more information, see [Use Sensitive Data Protection data in
    /// context-aware
    /// analytics](https://cloud.google.com/chronicle/docs/detection/usecase-dlp-high-risk-user-download).
    indirect case publishToChronicle(DataProfileAction.PublishToChronicle?)
    /// Publishes findings to Security Command Center for each data profile.
    indirect case publishToScc(DataProfileAction.PublishToSecurityCommandCenter?)
    /// Tags the profiled resources with the specified tag values.
    indirect case tagResources(DataProfileAction.TagResources?)
    /// Publishes a portion of each profile to Dataplex Universal Catalog with
    /// the aspect type Sensitive Data Protection Profile.
    indirect case publishToDataplexCatalog(DataProfileAction.PublishToDataplexCatalog?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.DataProfileAction"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
