// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Configuration for setting up a job to scan resources for profile generation.
/// Only one data profile configuration may exist per organization, folder,
/// or project.
///
/// The generated data profiles are retained according to the
/// [data retention policy]
/// (https://cloud.google.com/sensitive-data-protection/docs/data-profiles#retention).
public struct DataProfileJobConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The data to scan.
  public var location: DataProfileLocation? = nil

  /// The project that will run the scan. The DLP service
  /// account that exists within this project must have access to all resources
  /// that are profiled, and the DLP API must be enabled.
  public var projectId: Swift.String = Swift.String()

  /// Must be set only when scanning other clouds.
  public var otherCloudStartingLocation: OtherCloudDiscoveryStartingLocation? = nil

  /// Detection logic for profile generation.
  ///
  /// Not all template features are used by profiles. FindingLimits,
  /// include_quote and exclude_info_types have no impact on
  /// data profiling.
  ///
  /// Multiple templates may be provided if there is data in multiple regions.
  /// At most one template must be specified per-region (including "global").
  /// Each region is scanned using the applicable template. If no region-specific
  /// template is specified, but a "global" template is specified, it will be
  /// copied to that region and used instead. If no global or region-specific
  /// template is provided for a region with data, that region's data will not be
  /// scanned.
  ///
  /// For more information, see
  /// https://cloud.google.com/sensitive-data-protection/docs/data-profiles#data-residency.
  public var inspectTemplates: [Swift.String] = []

  /// Actions to execute at the completion of the job.
  public var dataProfileActions: [DataProfileAction] = []

  /// Initialize a new instance of `DataProfileJobConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataProfileJobConfig().with { $0.location = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.DataProfileJobConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
