// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Pub/Sub topic message for a DataProfileAction.PubSubNotification event.
/// To receive a message of protocol buffer schema type, convert the message data
/// to an object of this proto class.
public struct DataProfilePubSubMessage: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// If `DetailLevel` is `TABLE_PROFILE` this will be fully populated.
  /// Otherwise, if `DetailLevel` is `RESOURCE_NAME`, then only `name` and
  /// `full_resource` will be populated.
  public var profile: TableDataProfile? = nil

  /// If `DetailLevel` is `FILE_STORE_PROFILE` this will be fully populated.
  /// Otherwise, if `DetailLevel` is `RESOURCE_NAME`, then only `name` and
  /// `file_store_path` will be populated.
  public var fileStoreProfile: FileStoreDataProfile? = nil

  /// The event that caused the Pub/Sub message to be sent.
  public var event: DataProfileAction.EventType = DataProfileAction.EventType()

  /// Initialize a new instance of `DataProfilePubSubMessage`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataProfilePubSubMessage().with { $0.profile = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.DataProfilePubSubMessage"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
