// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The results of a [Deidentify][google.privacy.dlp.v2.Action.Deidentify] action
/// from an inspect job.
///
/// [google.privacy.dlp.v2.Action.Deidentify]: <doc:Action/Deidentify>
public struct DeidentifyDataSourceDetails: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// De-identification config used for the request.
  public var requestedOptions: DeidentifyDataSourceDetails.RequestedDeidentifyOptions? = nil

  /// Stats about the de-identification operation.
  public var deidentifyStats: DeidentifyDataSourceStats? = nil

  /// Initialize a new instance of `DeidentifyDataSourceDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DeidentifyDataSourceDetails().with { $0.requestedOptions = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// De-identification options.
  public struct RequestedDeidentifyOptions: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Snapshot of the state of the `DeidentifyTemplate` from the
    /// [Deidentify][google.privacy.dlp.v2.Action.Deidentify] action at the time
    /// this job was run.
    ///
    /// [google.privacy.dlp.v2.Action.Deidentify]: <doc:Action/Deidentify>
    public var snapshotDeidentifyTemplate: DeidentifyTemplate? = nil

    /// Snapshot of the state of the structured `DeidentifyTemplate` from the
    /// `Deidentify` action at the time this job was run.
    public var snapshotStructuredDeidentifyTemplate: DeidentifyTemplate? = nil

    /// Snapshot of the state of the image transformation `DeidentifyTemplate`
    /// from the `Deidentify` action at the time this job was run.
    public var snapshotImageRedactTemplate: DeidentifyTemplate? = nil

    /// Initialize a new instance of `RequestedDeidentifyOptions`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RequestedDeidentifyOptions().with { $0.snapshotDeidentifyTemplate = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.privacy.dlp.v2.DeidentifyDataSourceDetails.RequestedDeidentifyOptions"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.DeidentifyDataSourceDetails"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
