// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// How often existing tables should have their profiles refreshed.
/// New tables are scanned as quickly as possible depending on system
/// capacity.
public struct DiscoveryCloudSqlGenerationCadence: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// When to reprofile if the schema has changed.
  public var schemaModifiedCadence: DiscoveryCloudSqlGenerationCadence.SchemaModifiedCadence? = nil

  /// Data changes (non-schema changes) in Cloud SQL tables can't trigger
  /// reprofiling. If you set this field, profiles are refreshed at this
  /// frequency regardless of whether the underlying tables have changed.
  /// Defaults to never.
  public var refreshFrequency: DataProfileUpdateFrequency = DataProfileUpdateFrequency()

  /// Governs when to update data profiles when the inspection rules
  /// defined by the `InspectTemplate` change.
  /// If not set, changing the template will not cause a data profile to update.
  public var inspectTemplateModifiedCadence: DiscoveryInspectTemplateModifiedCadence? = nil

  /// Initialize a new instance of `DiscoveryCloudSqlGenerationCadence`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DiscoveryCloudSqlGenerationCadence().with { $0.schemaModifiedCadence = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// How frequently to modify the profile when the table's schema is modified.
  public struct SchemaModifiedCadence: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The types of schema modifications to consider.
    /// Defaults to NEW_COLUMNS.
    public var types:
      [DiscoveryCloudSqlGenerationCadence.SchemaModifiedCadence.CloudSqlSchemaModification] = []

    /// Frequency to regenerate data profiles when the schema is modified.
    /// Defaults to monthly.
    public var frequency: DataProfileUpdateFrequency = DataProfileUpdateFrequency()

    /// Initialize a new instance of `SchemaModifiedCadence`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SchemaModifiedCadence().with { $0.types = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// The type of modification that causes a profile update.
    public enum CloudSqlSchemaModification: Codable, Equatable, Sendable {
      /// Unused.
      case sqlSchemaModificationUnspecified
      /// New columns have appeared.
      case newColumns
      /// Columns have been removed from the table.
      case removedColumns
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .sqlSchemaModificationUnspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .sqlSchemaModificationUnspecified: return 0
        case .newColumns: return 1
        case .removedColumns: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .sqlSchemaModificationUnspecified: return "SQL_SCHEMA_MODIFICATION_UNSPECIFIED"
        case .newColumns: return "NEW_COLUMNS"
        case .removedColumns: return "REMOVED_COLUMNS"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CloudSqlSchemaModification/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "SQL_SCHEMA_MODIFICATION_UNSPECIFIED": self = .sqlSchemaModificationUnspecified
        case "NEW_COLUMNS": self = .newColumns
        case "REMOVED_COLUMNS": self = .removedColumns
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CloudSqlSchemaModification/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .sqlSchemaModificationUnspecified
        case 1: self = .newColumns
        case 2: self = .removedColumns
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .sqlSchemaModificationUnspecified: return try container.encode(0)
        case .newColumns: return try container.encode(1)
        case .removedColumns: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.privacy.dlp.v2.DiscoveryCloudSqlGenerationCadence.SchemaModifiedCadence"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.DiscoveryCloudSqlGenerationCadence"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
