// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The cadence at which to update data profiles when a table is modified.
public struct DiscoveryTableModifiedCadence: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The type of events to consider when deciding if the table has been
  /// modified and should have the profile updated. Defaults to
  /// MODIFIED_TIMESTAMP.
  public var types: [BigQueryTableModification] = []

  /// How frequently data profiles can be updated when tables are modified.
  /// Defaults to never.
  public var frequency: DataProfileUpdateFrequency = DataProfileUpdateFrequency()

  /// Initialize a new instance of `DiscoveryTableModifiedCadence`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DiscoveryTableModifiedCadence().with { $0.types = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.DiscoveryTableModifiedCadence"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
