// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Requirements that must be true before a Cloud Storage bucket or object is
/// scanned in discovery for the first time. There is an AND relationship between
/// the top-level attributes.
public struct DiscoveryCloudStorageConditions: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Only objects with the specified attributes will be scanned. If an
  /// object has one of the specified attributes but is inside an excluded
  /// bucket, it will not be scanned. Defaults to [ALL_SUPPORTED_OBJECTS]. A
  /// profile will be created even if no objects match the
  /// included_object_attributes.
  public var includedObjectAttributes:
    [DiscoveryCloudStorageConditions.CloudStorageObjectAttribute] = []

  /// Required. Only objects with the specified attributes will be scanned.
  /// Defaults to [ALL_SUPPORTED_BUCKETS] if unset.
  public var includedBucketAttributes:
    [DiscoveryCloudStorageConditions.CloudStorageBucketAttribute] = []

  /// Initialize a new instance of `DiscoveryCloudStorageConditions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DiscoveryCloudStorageConditions().with { $0.includedObjectAttributes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The attribute of an object. See
  /// https://cloud.google.com/storage/docs/storage-classes for more information
  /// on storage classes.
  public enum CloudStorageObjectAttribute: Codable, Equatable, Sendable {
    /// Unused.
    case unspecified
    /// Scan objects regardless of the attribute.
    case allSupportedObjects
    /// Scan objects with the standard storage class.
    case standard
    /// Scan objects with the nearline storage class. This will incur retrieval
    /// fees.
    case nearline
    /// Scan objects with the coldline storage class. This will incur retrieval
    /// fees.
    case coldline
    /// Scan objects with the archive storage class. This will incur retrieval
    /// fees.
    case archive
    /// Scan objects with the regional storage class.
    case regional
    /// Scan objects with the multi-regional storage class.
    case multiRegional
    /// Scan objects with the dual-regional storage class. This will incur
    /// retrieval fees.
    case durableReducedAvailability
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .allSupportedObjects: return 1
      case .standard: return 2
      case .nearline: return 3
      case .coldline: return 4
      case .archive: return 5
      case .regional: return 6
      case .multiRegional: return 7
      case .durableReducedAvailability: return 8
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CLOUD_STORAGE_OBJECT_ATTRIBUTE_UNSPECIFIED"
      case .allSupportedObjects: return "ALL_SUPPORTED_OBJECTS"
      case .standard: return "STANDARD"
      case .nearline: return "NEARLINE"
      case .coldline: return "COLDLINE"
      case .archive: return "ARCHIVE"
      case .regional: return "REGIONAL"
      case .multiRegional: return "MULTI_REGIONAL"
      case .durableReducedAvailability: return "DURABLE_REDUCED_AVAILABILITY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CloudStorageObjectAttribute/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CLOUD_STORAGE_OBJECT_ATTRIBUTE_UNSPECIFIED": self = .unspecified
      case "ALL_SUPPORTED_OBJECTS": self = .allSupportedObjects
      case "STANDARD": self = .standard
      case "NEARLINE": self = .nearline
      case "COLDLINE": self = .coldline
      case "ARCHIVE": self = .archive
      case "REGIONAL": self = .regional
      case "MULTI_REGIONAL": self = .multiRegional
      case "DURABLE_REDUCED_AVAILABILITY": self = .durableReducedAvailability
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CloudStorageObjectAttribute/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .allSupportedObjects
      case 2: self = .standard
      case 3: self = .nearline
      case 4: self = .coldline
      case 5: self = .archive
      case 6: self = .regional
      case 7: self = .multiRegional
      case 8: self = .durableReducedAvailability
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .allSupportedObjects: return try container.encode(1)
      case .standard: return try container.encode(2)
      case .nearline: return try container.encode(3)
      case .coldline: return try container.encode(4)
      case .archive: return try container.encode(5)
      case .regional: return try container.encode(6)
      case .multiRegional: return try container.encode(7)
      case .durableReducedAvailability: return try container.encode(8)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The attribute of a bucket.
  public enum CloudStorageBucketAttribute: Codable, Equatable, Sendable {
    /// Unused.
    case unspecified
    /// Scan buckets regardless of the attribute.
    case allSupportedBuckets
    /// Buckets with [Autoclass](https://cloud.google.com/storage/docs/autoclass)
    /// disabled. Only one of
    /// AUTOCLASS_DISABLED or AUTOCLASS_ENABLED should be set.
    case autoclassDisabled
    /// Buckets with [Autoclass](https://cloud.google.com/storage/docs/autoclass)
    /// enabled. Only one of
    /// AUTOCLASS_DISABLED or AUTOCLASS_ENABLED should be set. Scanning
    /// Autoclass-enabled buckets can affect object storage classes.
    case autoclassEnabled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .allSupportedBuckets: return 1
      case .autoclassDisabled: return 2
      case .autoclassEnabled: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "CLOUD_STORAGE_BUCKET_ATTRIBUTE_UNSPECIFIED"
      case .allSupportedBuckets: return "ALL_SUPPORTED_BUCKETS"
      case .autoclassDisabled: return "AUTOCLASS_DISABLED"
      case .autoclassEnabled: return "AUTOCLASS_ENABLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:CloudStorageBucketAttribute/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "CLOUD_STORAGE_BUCKET_ATTRIBUTE_UNSPECIFIED": self = .unspecified
      case "ALL_SUPPORTED_BUCKETS": self = .allSupportedBuckets
      case "AUTOCLASS_DISABLED": self = .autoclassDisabled
      case "AUTOCLASS_ENABLED": self = .autoclassEnabled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:CloudStorageBucketAttribute/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .allSupportedBuckets
      case 2: self = .autoclassDisabled
      case 3: self = .autoclassEnabled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .allSupportedBuckets: return try container.encode(1)
      case .autoclassDisabled: return try container.encode(2)
      case .autoclassEnabled: return try container.encode(3)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.DiscoveryCloudStorageConditions"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
