// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Combines all of the information about a DLP job.
public struct DlpJob: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The server-assigned name.
  public var name: Swift.String = Swift.String()

  /// The type of job.
  public var type: DlpJobType = DlpJobType()

  /// Output only. State of a job.
  public var state: DlpJob.JobState = DlpJob.JobState()

  /// Output only. Time when the job was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Time when the job started.
  public var startTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Time when the job finished.
  public var endTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. Time when the job was last modified by the system.
  public var lastModified: GoogleCloudWKT.Timestamp? = nil

  /// Output only. If created by a job trigger, the resource name of the trigger
  /// that instantiated the job.
  public var jobTriggerName: Swift.String = Swift.String()

  /// Output only. A stream of errors encountered running the job.
  public var errors: [Error] = []

  /// Output only. Events that should occur after the job has completed.
  public var actionDetails: [ActionDetails] = []

  /// Job details.
  public var details: OneOf_Details? = nil

  /// Initialize a new instance of `DlpJob`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DlpJob().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case name = "name"
    case type = "type"
    case state = "state"
    case riskDetails = "riskDetails"
    case inspectDetails = "inspectDetails"
    case createTime = "createTime"
    case startTime = "startTime"
    case endTime = "endTime"
    case lastModified = "lastModified"
    case jobTriggerName = "jobTriggerName"
    case errors = "errors"
    case actionDetails = "actionDetails"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.type = try container.decode(DlpJobType.self, forKey: .type)
    self.state = try container.decode(DlpJob.JobState.self, forKey: .state)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.startTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .startTime)
    self.endTime = try container.decodeIfPresent(GoogleCloudWKT.Timestamp.self, forKey: .endTime)
    self.lastModified = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .lastModified)
    self.jobTriggerName = try container.decode(Swift.String.self, forKey: .jobTriggerName)
    self.errors = try container.decode([Error].self, forKey: .errors)
    self.actionDetails = try container.decode([ActionDetails].self, forKey: .actionDetails)

    var details: OneOf_Details? = nil
    let detailsCheckAndSet = {
      if details != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'details'"))
      }
      details = $0
    }
    if let riskDetails = try container.decodeIfPresent(
      AnalyzeDataSourceRiskDetails?.self, forKey: .riskDetails)
    {
      try detailsCheckAndSet(.riskDetails(riskDetails))
    }
    if let inspectDetails = try container.decodeIfPresent(
      InspectDataSourceDetails?.self, forKey: .inspectDetails)
    {
      try detailsCheckAndSet(.inspectDetails(inspectDetails))
    }
    self.details = details
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.startTime, forKey: .startTime)
    try container.encode(self.endTime, forKey: .endTime)
    try container.encode(self.lastModified, forKey: .lastModified)
    try container.encode(self.jobTriggerName, forKey: .jobTriggerName)
    try container.encode(self.errors, forKey: .errors)
    try container.encode(self.actionDetails, forKey: .actionDetails)

    if let choice = self.details {
      switch choice {
      case .riskDetails(let value):
        try container.encode(value, forKey: .riskDetails)
      case .inspectDetails(let value):
        try container.encode(value, forKey: .inspectDetails)
      }
    }
  }

  /// Possible states of a job. New items may be added.
  public enum JobState: Codable, Equatable, Sendable {
    /// Unused.
    case unspecified
    /// The job has not yet started.
    case pending
    /// The job is currently running. Once a job has finished it will transition
    /// to FAILED or DONE.
    case running
    /// The job is no longer running.
    case done
    /// The job was canceled before it could be completed.
    case canceled
    /// The job had an error and did not complete.
    case failed
    /// The job is currently accepting findings via hybridInspect.
    /// A hybrid job in ACTIVE state may continue to have findings added to it
    /// through the calling of hybridInspect. After the job has finished no more
    /// calls to hybridInspect may be made. ACTIVE jobs can transition to DONE.
    case active
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .pending: return 1
      case .running: return 2
      case .done: return 3
      case .canceled: return 4
      case .failed: return 5
      case .active: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "JOB_STATE_UNSPECIFIED"
      case .pending: return "PENDING"
      case .running: return "RUNNING"
      case .done: return "DONE"
      case .canceled: return "CANCELED"
      case .failed: return "FAILED"
      case .active: return "ACTIVE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:JobState/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "JOB_STATE_UNSPECIFIED": self = .unspecified
      case "PENDING": self = .pending
      case "RUNNING": self = .running
      case "DONE": self = .done
      case "CANCELED": self = .canceled
      case "FAILED": self = .failed
      case "ACTIVE": self = .active
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:JobState/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .pending
      case 2: self = .running
      case 3: self = .done
      case 4: self = .canceled
      case 5: self = .failed
      case 6: self = .active
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .pending: return try container.encode(1)
      case .running: return try container.encode(2)
      case .done: return try container.encode(3)
      case .canceled: return try container.encode(4)
      case .failed: return try container.encode(5)
      case .active: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Job details.
  public enum OneOf_Details: Codable, Equatable, Sendable {
    /// Results from analyzing risk of a data source.
    indirect case riskDetails(AnalyzeDataSourceRiskDetails?)
    /// Results from inspecting a data source.
    indirect case inspectDetails(InspectDataSourceDetails?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.DlpJob"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
