// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWKT
import GoogleCloudGax

extension Clients {
  protocol DlpServiceStub: Sendable {
    func inspectContent(
      request: InspectContentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.InspectContentResponse

    func redactImage(
      request: RedactImageRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.RedactImageResponse

    func deidentifyContent(
      request: DeidentifyContentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.DeidentifyContentResponse

    func reidentifyContent(
      request: ReidentifyContentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ReidentifyContentResponse

    func listInfoTypes(
      request: ListInfoTypesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ListInfoTypesResponse

    func createInspectTemplate(
      request: CreateInspectTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.InspectTemplate

    func updateInspectTemplate(
      request: UpdateInspectTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.InspectTemplate

    func getInspectTemplate(
      request: GetInspectTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.InspectTemplate

    func listInspectTemplates(
      request: ListInspectTemplatesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ListInspectTemplatesResponse

    func deleteInspectTemplate(
      request: DeleteInspectTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func createDeidentifyTemplate(
      request: CreateDeidentifyTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.DeidentifyTemplate

    func updateDeidentifyTemplate(
      request: UpdateDeidentifyTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.DeidentifyTemplate

    func getDeidentifyTemplate(
      request: GetDeidentifyTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.DeidentifyTemplate

    func listDeidentifyTemplates(
      request: ListDeidentifyTemplatesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ListDeidentifyTemplatesResponse

    func deleteDeidentifyTemplate(
      request: DeleteDeidentifyTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func createJobTrigger(
      request: CreateJobTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.JobTrigger

    func updateJobTrigger(
      request: UpdateJobTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.JobTrigger

    func hybridInspectJobTrigger(
      request: HybridInspectJobTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.HybridInspectResponse

    func getJobTrigger(
      request: GetJobTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.JobTrigger

    func listJobTriggers(
      request: ListJobTriggersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ListJobTriggersResponse

    func deleteJobTrigger(
      request: DeleteJobTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func activateJobTrigger(
      request: ActivateJobTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.DlpJob

    func createDiscoveryConfig(
      request: CreateDiscoveryConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.DiscoveryConfig

    func updateDiscoveryConfig(
      request: UpdateDiscoveryConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.DiscoveryConfig

    func getDiscoveryConfig(
      request: GetDiscoveryConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.DiscoveryConfig

    func listDiscoveryConfigs(
      request: ListDiscoveryConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ListDiscoveryConfigsResponse

    func deleteDiscoveryConfig(
      request: DeleteDiscoveryConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func createDlpJob(
      request: CreateDlpJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.DlpJob

    func listDlpJobs(
      request: ListDlpJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ListDlpJobsResponse

    func getDlpJob(
      request: GetDlpJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.DlpJob

    func deleteDlpJob(
      request: DeleteDlpJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func cancelDlpJob(
      request: CancelDlpJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func createStoredInfoType(
      request: CreateStoredInfoTypeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.StoredInfoType

    func updateStoredInfoType(
      request: UpdateStoredInfoTypeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.StoredInfoType

    func getStoredInfoType(
      request: GetStoredInfoTypeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.StoredInfoType

    func listStoredInfoTypes(
      request: ListStoredInfoTypesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ListStoredInfoTypesResponse

    func deleteStoredInfoType(
      request: DeleteStoredInfoTypeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func listProjectDataProfiles(
      request: ListProjectDataProfilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ListProjectDataProfilesResponse

    func listTableDataProfiles(
      request: ListTableDataProfilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ListTableDataProfilesResponse

    func listColumnDataProfiles(
      request: ListColumnDataProfilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ListColumnDataProfilesResponse

    func getProjectDataProfile(
      request: GetProjectDataProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ProjectDataProfile

    func listFileStoreDataProfiles(
      request: ListFileStoreDataProfilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ListFileStoreDataProfilesResponse

    func getFileStoreDataProfile(
      request: GetFileStoreDataProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.FileStoreDataProfile

    func deleteFileStoreDataProfile(
      request: DeleteFileStoreDataProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func getTableDataProfile(
      request: GetTableDataProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.TableDataProfile

    func getColumnDataProfile(
      request: GetColumnDataProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ColumnDataProfile

    func deleteTableDataProfile(
      request: DeleteTableDataProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func hybridInspectDlpJob(
      request: HybridInspectDlpJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.HybridInspectResponse

    func finishDlpJob(
      request: FinishDlpJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func createConnection(
      request: CreateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.Connection

    func getConnection(
      request: GetConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.Connection

    func listConnections(
      request: ListConnectionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ListConnectionsResponse

    func searchConnections(
      request: SearchConnectionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.SearchConnectionsResponse

    func deleteConnection(
      request: DeleteConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func updateConnection(
      request: UpdateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.Connection
  }
}
