// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class DlpServiceRetry: DlpServiceStub {
    let inner: any DlpServiceStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any DlpServiceStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func inspectContent(
      request: InspectContentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.InspectContentResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: InspectContentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.InspectContentResponse
          in
          return try await self.inner.inspectContent(request: r, options: o)
        })
    }

    public func redactImage(
      request: RedactImageRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.RedactImageResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: RedactImageRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.RedactImageResponse
          in
          return try await self.inner.redactImage(request: r, options: o)
        })
    }

    public func deidentifyContent(
      request: DeidentifyContentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.DeidentifyContentResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeidentifyContentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.DeidentifyContentResponse
          in
          return try await self.inner.deidentifyContent(request: r, options: o)
        })
    }

    public func reidentifyContent(
      request: ReidentifyContentRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ReidentifyContentResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ReidentifyContentRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.ReidentifyContentResponse
          in
          return try await self.inner.reidentifyContent(request: r, options: o)
        })
    }

    public func listInfoTypes(
      request: ListInfoTypesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ListInfoTypesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListInfoTypesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.ListInfoTypesResponse
          in
          return try await self.inner.listInfoTypes(request: r, options: o)
        })
    }

    public func createInspectTemplate(
      request: CreateInspectTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.InspectTemplate {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateInspectTemplateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.InspectTemplate
          in
          return try await self.inner.createInspectTemplate(request: r, options: o)
        })
    }

    public func updateInspectTemplate(
      request: UpdateInspectTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.InspectTemplate {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateInspectTemplateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.InspectTemplate
          in
          return try await self.inner.updateInspectTemplate(request: r, options: o)
        })
    }

    public func getInspectTemplate(
      request: GetInspectTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.InspectTemplate {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetInspectTemplateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.InspectTemplate
          in
          return try await self.inner.getInspectTemplate(request: r, options: o)
        })
    }

    public func listInspectTemplates(
      request: ListInspectTemplatesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ListInspectTemplatesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListInspectTemplatesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.ListInspectTemplatesResponse
          in
          return try await self.inner.listInspectTemplates(request: r, options: o)
        })
    }

    public func deleteInspectTemplate(
      request: DeleteInspectTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteInspectTemplateRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteInspectTemplate(request: r, options: o)
        })
    }

    public func createDeidentifyTemplate(
      request: CreateDeidentifyTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.DeidentifyTemplate {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateDeidentifyTemplateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.DeidentifyTemplate
          in
          return try await self.inner.createDeidentifyTemplate(request: r, options: o)
        })
    }

    public func updateDeidentifyTemplate(
      request: UpdateDeidentifyTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.DeidentifyTemplate {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateDeidentifyTemplateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.DeidentifyTemplate
          in
          return try await self.inner.updateDeidentifyTemplate(request: r, options: o)
        })
    }

    public func getDeidentifyTemplate(
      request: GetDeidentifyTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.DeidentifyTemplate {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetDeidentifyTemplateRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.DeidentifyTemplate
          in
          return try await self.inner.getDeidentifyTemplate(request: r, options: o)
        })
    }

    public func listDeidentifyTemplates(
      request: ListDeidentifyTemplatesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ListDeidentifyTemplatesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListDeidentifyTemplatesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.ListDeidentifyTemplatesResponse
          in
          return try await self.inner.listDeidentifyTemplates(request: r, options: o)
        })
    }

    public func deleteDeidentifyTemplate(
      request: DeleteDeidentifyTemplateRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteDeidentifyTemplateRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteDeidentifyTemplate(request: r, options: o)
        })
    }

    public func createJobTrigger(
      request: CreateJobTriggerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.JobTrigger {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateJobTriggerRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.JobTrigger
          in
          return try await self.inner.createJobTrigger(request: r, options: o)
        })
    }

    public func updateJobTrigger(
      request: UpdateJobTriggerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.JobTrigger {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateJobTriggerRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.JobTrigger
          in
          return try await self.inner.updateJobTrigger(request: r, options: o)
        })
    }

    public func hybridInspectJobTrigger(
      request: HybridInspectJobTriggerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.HybridInspectResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: HybridInspectJobTriggerRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.HybridInspectResponse
          in
          return try await self.inner.hybridInspectJobTrigger(request: r, options: o)
        })
    }

    public func getJobTrigger(
      request: GetJobTriggerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.JobTrigger {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetJobTriggerRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.JobTrigger
          in
          return try await self.inner.getJobTrigger(request: r, options: o)
        })
    }

    public func listJobTriggers(
      request: ListJobTriggersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ListJobTriggersResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListJobTriggersRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.ListJobTriggersResponse
          in
          return try await self.inner.listJobTriggers(request: r, options: o)
        })
    }

    public func deleteJobTrigger(
      request: DeleteJobTriggerRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteJobTriggerRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteJobTrigger(request: r, options: o)
        })
    }

    public func activateJobTrigger(
      request: ActivateJobTriggerRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.DlpJob {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: ActivateJobTriggerRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.DlpJob
          in
          return try await self.inner.activateJobTrigger(request: r, options: o)
        })
    }

    public func createDiscoveryConfig(
      request: CreateDiscoveryConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.DiscoveryConfig {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateDiscoveryConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.DiscoveryConfig
          in
          return try await self.inner.createDiscoveryConfig(request: r, options: o)
        })
    }

    public func updateDiscoveryConfig(
      request: UpdateDiscoveryConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.DiscoveryConfig {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateDiscoveryConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.DiscoveryConfig
          in
          return try await self.inner.updateDiscoveryConfig(request: r, options: o)
        })
    }

    public func getDiscoveryConfig(
      request: GetDiscoveryConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.DiscoveryConfig {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetDiscoveryConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.DiscoveryConfig
          in
          return try await self.inner.getDiscoveryConfig(request: r, options: o)
        })
    }

    public func listDiscoveryConfigs(
      request: ListDiscoveryConfigsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ListDiscoveryConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListDiscoveryConfigsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.ListDiscoveryConfigsResponse
          in
          return try await self.inner.listDiscoveryConfigs(request: r, options: o)
        })
    }

    public func deleteDiscoveryConfig(
      request: DeleteDiscoveryConfigRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteDiscoveryConfigRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteDiscoveryConfig(request: r, options: o)
        })
    }

    public func createDlpJob(
      request: CreateDlpJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.DlpJob {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateDlpJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.DlpJob
          in
          return try await self.inner.createDlpJob(request: r, options: o)
        })
    }

    public func listDlpJobs(
      request: ListDlpJobsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ListDlpJobsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListDlpJobsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.ListDlpJobsResponse
          in
          return try await self.inner.listDlpJobs(request: r, options: o)
        })
    }

    public func getDlpJob(
      request: GetDlpJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.DlpJob {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetDlpJobRequest, o: GoogleGax.RequestOptions) async throws -> GoogleCloudDLPV2.DlpJob
          in
          return try await self.inner.getDlpJob(request: r, options: o)
        })
    }

    public func deleteDlpJob(
      request: DeleteDlpJobRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteDlpJobRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteDlpJob(request: r, options: o)
        })
    }

    public func cancelDlpJob(
      request: CancelDlpJobRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: CancelDlpJobRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.cancelDlpJob(request: r, options: o)
        })
    }

    public func createStoredInfoType(
      request: CreateStoredInfoTypeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.StoredInfoType {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateStoredInfoTypeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.StoredInfoType
          in
          return try await self.inner.createStoredInfoType(request: r, options: o)
        })
    }

    public func updateStoredInfoType(
      request: UpdateStoredInfoTypeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.StoredInfoType {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateStoredInfoTypeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.StoredInfoType
          in
          return try await self.inner.updateStoredInfoType(request: r, options: o)
        })
    }

    public func getStoredInfoType(
      request: GetStoredInfoTypeRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.StoredInfoType {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetStoredInfoTypeRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.StoredInfoType
          in
          return try await self.inner.getStoredInfoType(request: r, options: o)
        })
    }

    public func listStoredInfoTypes(
      request: ListStoredInfoTypesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ListStoredInfoTypesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListStoredInfoTypesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.ListStoredInfoTypesResponse
          in
          return try await self.inner.listStoredInfoTypes(request: r, options: o)
        })
    }

    public func deleteStoredInfoType(
      request: DeleteStoredInfoTypeRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteStoredInfoTypeRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteStoredInfoType(request: r, options: o)
        })
    }

    public func listProjectDataProfiles(
      request: ListProjectDataProfilesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ListProjectDataProfilesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListProjectDataProfilesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.ListProjectDataProfilesResponse
          in
          return try await self.inner.listProjectDataProfiles(request: r, options: o)
        })
    }

    public func listTableDataProfiles(
      request: ListTableDataProfilesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ListTableDataProfilesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListTableDataProfilesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.ListTableDataProfilesResponse
          in
          return try await self.inner.listTableDataProfiles(request: r, options: o)
        })
    }

    public func listColumnDataProfiles(
      request: ListColumnDataProfilesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ListColumnDataProfilesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListColumnDataProfilesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.ListColumnDataProfilesResponse
          in
          return try await self.inner.listColumnDataProfiles(request: r, options: o)
        })
    }

    public func getProjectDataProfile(
      request: GetProjectDataProfileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ProjectDataProfile {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetProjectDataProfileRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.ProjectDataProfile
          in
          return try await self.inner.getProjectDataProfile(request: r, options: o)
        })
    }

    public func listFileStoreDataProfiles(
      request: ListFileStoreDataProfilesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ListFileStoreDataProfilesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListFileStoreDataProfilesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.ListFileStoreDataProfilesResponse
          in
          return try await self.inner.listFileStoreDataProfiles(request: r, options: o)
        })
    }

    public func getFileStoreDataProfile(
      request: GetFileStoreDataProfileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.FileStoreDataProfile {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetFileStoreDataProfileRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.FileStoreDataProfile
          in
          return try await self.inner.getFileStoreDataProfile(request: r, options: o)
        })
    }

    public func deleteFileStoreDataProfile(
      request: DeleteFileStoreDataProfileRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteFileStoreDataProfileRequest, o: GoogleGax.RequestOptions) async throws -> Void
          in
          return try await self.inner.deleteFileStoreDataProfile(request: r, options: o)
        })
    }

    public func getTableDataProfile(
      request: GetTableDataProfileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.TableDataProfile {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetTableDataProfileRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.TableDataProfile
          in
          return try await self.inner.getTableDataProfile(request: r, options: o)
        })
    }

    public func getColumnDataProfile(
      request: GetColumnDataProfileRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ColumnDataProfile {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetColumnDataProfileRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.ColumnDataProfile
          in
          return try await self.inner.getColumnDataProfile(request: r, options: o)
        })
    }

    public func deleteTableDataProfile(
      request: DeleteTableDataProfileRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteTableDataProfileRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteTableDataProfile(request: r, options: o)
        })
    }

    public func hybridInspectDlpJob(
      request: HybridInspectDlpJobRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.HybridInspectResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: HybridInspectDlpJobRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.HybridInspectResponse
          in
          return try await self.inner.hybridInspectDlpJob(request: r, options: o)
        })
    }

    public func finishDlpJob(
      request: FinishDlpJobRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: FinishDlpJobRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.finishDlpJob(request: r, options: o)
        })
    }

    public func createConnection(
      request: CreateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.Connection {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateConnectionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.Connection
          in
          return try await self.inner.createConnection(request: r, options: o)
        })
    }

    public func getConnection(
      request: GetConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.Connection {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetConnectionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.Connection
          in
          return try await self.inner.getConnection(request: r, options: o)
        })
    }

    public func listConnections(
      request: ListConnectionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ListConnectionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListConnectionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.ListConnectionsResponse
          in
          return try await self.inner.listConnections(request: r, options: o)
        })
    }

    public func searchConnections(
      request: SearchConnectionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.SearchConnectionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: SearchConnectionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.SearchConnectionsResponse
          in
          return try await self.inner.searchConnections(request: r, options: o)
        })
    }

    public func deleteConnection(
      request: DeleteConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteConnectionRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteConnection(request: r, options: o)
        })
    }

    public func updateConnection(
      request: UpdateConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.Connection {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateConnectionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.Connection
          in
          return try await self.inner.updateConnection(request: r, options: o)
        })
    }

    public func createContentPolicy(
      request: CreateContentPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ContentPolicy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateContentPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.ContentPolicy
          in
          return try await self.inner.createContentPolicy(request: r, options: o)
        })
    }

    public func updateContentPolicy(
      request: UpdateContentPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ContentPolicy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateContentPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.ContentPolicy
          in
          return try await self.inner.updateContentPolicy(request: r, options: o)
        })
    }

    public func getContentPolicy(
      request: GetContentPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ContentPolicy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetContentPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.ContentPolicy
          in
          return try await self.inner.getContentPolicy(request: r, options: o)
        })
    }

    public func listContentPolicies(
      request: ListContentPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDLPV2.ListContentPoliciesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListContentPoliciesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudDLPV2.ListContentPoliciesResponse
          in
          return try await self.inner.listContentPolicies(request: r, options: o)
        })
    }

    public func deleteContentPolicy(
      request: DeleteContentPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteContentPolicyRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteContentPolicy(request: r, options: o)
        })
    }
  }
}
