// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The rule to exclude image findings based on spatial relationships with
/// other image findings. For example, exclude an image finding if it overlaps
/// with another image finding.
/// This rule is silently ignored if the content being inspected is not an image.
public struct ExcludeByImageFindings: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// A list of image-supported infoTypes—excluding [document
  ///  infoTypes](https://cloud.google.com/sensitive-data-protection/docs/infotypes-reference#documents)—to
  ///  be used as context for the exclusion rule. A finding is excluded if
  ///  its bounding box has the specified spatial relationship (defined by
  ///  `image_containment_type`) with a finding of an infoType in this list.
  ///
  ///  For example, if `InspectionRuleSet.info_types` includes
  ///  `OBJECT_TYPE/PERSON` and this `exclusion_rule` specifies `info_types` as
  ///  `OBJECT_TYPE/PERSON/PASSPORT` with `image_containment_type` set to
  ///  `encloses`, then `OBJECT_TYPE/PERSON` findings will be excluded if they
  ///  are fully contained within the bounding box of an
  ///  `OBJECT_TYPE/PERSON/PASSPORT` finding.
  public var infoTypes: [InfoType] = []

  /// Specifies the required spatial relationship between the bounding boxes
  /// of the target finding and the context infoType findings.
  public var imageContainmentType: ImageContainmentType? = nil

  /// Initialize a new instance of `ExcludeByImageFindings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExcludeByImageFindings().with { $0.infoTypes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.ExcludeByImageFindings"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
