// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The rule that specifies conditions when findings of infoTypes specified in
/// `InspectionRuleSet` are removed from results.
public struct ExclusionRule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// How the rule is applied, see MatchingType documentation for details.
  public var matchingType: MatchingType = MatchingType()

  /// Exclusion rule types.
  public var type: OneOf_Type? = nil

  /// Initialize a new instance of `ExclusionRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExclusionRule().with { $0.dictionary = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case dictionary = "dictionary"
    case regex = "regex"
    case excludeInfoTypes = "excludeInfoTypes"
    case excludeByHotword = "excludeByHotword"
    case excludeByImageFindings = "excludeByImageFindings"
    case matchingType = "matchingType"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.matchingType = try container.decode(MatchingType.self, forKey: .matchingType)

    var type: OneOf_Type? = nil
    let typeCheckAndSet = {
      if type != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'type'"
          ))
      }
      type = $0
    }
    if let dictionary = try container.decodeIfPresent(
      CustomInfoType.Dictionary?.self, forKey: .dictionary)
    {
      try typeCheckAndSet(.dictionary(dictionary))
    }
    if let regex = try container.decodeIfPresent(CustomInfoType.Regex?.self, forKey: .regex) {
      try typeCheckAndSet(.regex(regex))
    }
    if let excludeInfoTypes = try container.decodeIfPresent(
      ExcludeInfoTypes?.self, forKey: .excludeInfoTypes)
    {
      try typeCheckAndSet(.excludeInfoTypes(excludeInfoTypes))
    }
    if let excludeByHotword = try container.decodeIfPresent(
      ExcludeByHotword?.self, forKey: .excludeByHotword)
    {
      try typeCheckAndSet(.excludeByHotword(excludeByHotword))
    }
    if let excludeByImageFindings = try container.decodeIfPresent(
      ExcludeByImageFindings?.self, forKey: .excludeByImageFindings)
    {
      try typeCheckAndSet(.excludeByImageFindings(excludeByImageFindings))
    }
    self.type = type
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.matchingType, forKey: .matchingType)

    if let choice = self.type {
      switch choice {
      case .dictionary(let value):
        try container.encode(value, forKey: .dictionary)
      case .regex(let value):
        try container.encode(value, forKey: .regex)
      case .excludeInfoTypes(let value):
        try container.encode(value, forKey: .excludeInfoTypes)
      case .excludeByHotword(let value):
        try container.encode(value, forKey: .excludeByHotword)
      case .excludeByImageFindings(let value):
        try container.encode(value, forKey: .excludeByImageFindings)
      }
    }
  }

  /// Exclusion rule types.
  public enum OneOf_Type: Codable, Equatable, Sendable {
    /// Dictionary which defines the rule.
    indirect case dictionary(CustomInfoType.Dictionary?)
    /// Regular expression which defines the rule.
    indirect case regex(CustomInfoType.Regex?)
    /// Set of infoTypes for which findings would affect this rule.
    indirect case excludeInfoTypes(ExcludeInfoTypes?)
    /// Drop if the hotword rule is contained in the proximate context. For
    /// tabular data, the context includes the column name.
    indirect case excludeByHotword(ExcludeByHotword?)
    /// Exclude findings based on image containment rules. For example, exclude
    /// an image finding if it overlaps with another image finding.
    indirect case excludeByImageFindings(ExcludeByImageFindings?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.ExclusionRule"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
