// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Represents a file label.
public struct FileLabel: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The type of file label.
  public var type: OneOf_Type? = nil

  /// Initialize a new instance of `FileLabel`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FileLabel().with { $0.sensitivityLabel = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case sensitivityLabel = "sensitivityLabel"
    case googleDriveLabel = "googleDriveLabel"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var type: OneOf_Type? = nil
    let typeCheckAndSet = {
      if type != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'type'"
          ))
      }
      type = $0
    }
    if let sensitivityLabel = try container.decodeIfPresent(
      FileLabel.SensitivityLabelMetadata?.self, forKey: .sensitivityLabel)
    {
      try typeCheckAndSet(.sensitivityLabel(sensitivityLabel))
    }
    if let googleDriveLabel = try container.decodeIfPresent(
      FileLabel.GoogleDriveLabelMetadata?.self, forKey: .googleDriveLabel)
    {
      try typeCheckAndSet(.googleDriveLabel(googleDriveLabel))
    }
    self.type = type
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.type {
      switch choice {
      case .sensitivityLabel(let value):
        try container.encode(value, forKey: .sensitivityLabel)
      case .googleDriveLabel(let value):
        try container.encode(value, forKey: .googleDriveLabel)
      }
    }
  }

  /// Sensitivity labels published by Microsoft.
  public struct SensitivityLabelMetadata: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. The GUID of the sensitivity label.
    public var guid: Swift.String = Swift.String()

    /// Initialize a new instance of `SensitivityLabelMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SensitivityLabelMetadata().with { $0.guid = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.FileLabel.SensitivityLabelMetadata"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Google Drive labels published by Google.
  public struct GoogleDriveLabelMetadata: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The [label
    /// ID](https://developers.google.com/workspace/drive/labels/guides/overview)
    /// of the Google Drive label.
    public var labelId: Swift.String = Swift.String()

    /// The field values of the Google Drive label
    public var labelFields: [FileLabel.GoogleDriveLabelMetadata.LabelFieldMetadata] = []

    /// Initialize a new instance of `GoogleDriveLabelMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GoogleDriveLabelMetadata().with { $0.labelId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// The field values of the Google Drive label
    public struct LabelFieldMetadata: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// The identifier of the Label Field.
      public var id: Swift.String = Swift.String()

      /// The value of the Label Field.
      public var value: Value? = nil

      /// Initialize a new instance of `LabelFieldMetadata`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = LabelFieldMetadata().with { $0.id = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.privacy.dlp.v2.FileLabel.GoogleDriveLabelMetadata.LabelFieldMetadata"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.FileLabel.GoogleDriveLabelMetadata"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The type of file label.
  public enum OneOf_Type: Codable, Equatable, Sendable {
    /// Sensitivity labels published by Microsoft.
    indirect case sensitivityLabel(FileLabel.SensitivityLabelMetadata?)
    /// Google Drive labels published by Google.
    indirect case googleDriveLabel(FileLabel.GoogleDriveLabelMetadata?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.FileLabel"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
