// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The file cluster summary.
public struct FileClusterSummary: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The file cluster type.
  public var fileClusterType: FileClusterType? = nil

  /// InfoTypes detected in this cluster.
  public var fileStoreInfoTypeSummaries: [FileStoreInfoTypeSummary] = []

  /// The sensitivity score of this cluster. The score will be SENSITIVITY_LOW
  /// if nothing has been scanned.
  public var sensitivityScore: SensitivityScore? = nil

  /// The data risk level of this cluster. RISK_LOW if nothing has been
  /// scanned.
  public var dataRiskLevel: DataRiskLevel? = nil

  /// A list of errors detected while scanning this cluster. The list is
  /// truncated to 10 per cluster.
  public var errors: [Error] = []

  /// A sample of file types scanned in this cluster. Empty if no files were
  /// scanned. File extensions can be derived from the file name or the file
  /// content.
  public var fileExtensionsScanned: [FileExtensionInfo] = []

  /// A sample of file types seen in this cluster. Empty if no files were seen.
  /// File extensions can be derived from the file name or the file content.
  public var fileExtensionsSeen: [FileExtensionInfo] = []

  /// True if no files exist in this cluster. If the file store had more files
  /// than could be listed, this will be false even if no files for this cluster
  /// were seen and file_extensions_seen is empty.
  public var noFilesExist: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `FileClusterSummary`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FileClusterSummary().with { $0.fileClusterType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.FileClusterSummary"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
