// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents a piece of potentially sensitive content.
public struct Finding: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Resource name in format
  /// projects/{project}/locations/{location}/findings/{finding} Populated only
  /// when viewing persisted findings.
  public var name: Swift.String = Swift.String()

  /// The content that was found. Even if the content is not textual, it
  /// may be converted to a textual representation here.
  /// Provided if `include_quote` is true and the finding is
  /// less than or equal to 4096 bytes long. If the finding exceeds 4096 bytes
  /// in length, the quote may be omitted.
  public var quote: Swift.String = Swift.String()

  /// The type of content that might have been found.
  /// Provided if `excluded_types` is false.
  public var infoType: InfoType? = nil

  /// Confidence of how likely it is that the `info_type` is correct.
  public var likelihood: Likelihood = Likelihood()

  /// Where the content was found.
  public var location: Location? = nil

  /// Timestamp when finding was detected.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Contains data parsed from quotes. Only populated if include_quote was set
  /// to true and a supported infoType was requested. Currently supported
  /// infoTypes: DATE, DATE_OF_BIRTH and TIME.
  public var quoteInfo: QuoteInfo? = nil

  /// The job that stored the finding.
  public var resourceName: Swift.String = Swift.String()

  /// Job trigger name, if applicable, for this finding.
  public var triggerName: Swift.String = Swift.String()

  /// The labels associated with this `Finding`.
  ///
  /// Label keys must be between 1 and 63 characters long and must conform
  /// to the following regular expression: `[a-z]([-a-z0-9]*[a-z0-9])?`.
  ///
  /// Label values must be between 0 and 63 characters long and must conform
  /// to the regular expression `([a-z]([-a-z0-9]*[a-z0-9])?)?`.
  ///
  /// No more than 10 labels can be associated with a given finding.
  ///
  /// Examples:
  ///
  /// * `"environment" : "production"`
  /// * `"pipeline" : "etl"`
  public var labels: [Swift.String: Swift.String] = [:]

  /// Time the job started that produced this finding.
  public var jobCreateTime: GoogleCloudWkt.Timestamp? = nil

  /// The job that stored the finding.
  public var jobName: Swift.String = Swift.String()

  /// The unique finding id.
  public var findingId: Swift.String = Swift.String()

  /// Initialize a new instance of `Finding`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Finding().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.Finding"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
