// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Specifies the relationship between bounding boxes for image findings.
public struct ImageContainmentType: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The type of relationship to check between the target finding and the
  /// context finding.
  public var type: OneOf_Type? = nil

  /// Initialize a new instance of `ImageContainmentType`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ImageContainmentType().with { $0.encloses = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case encloses = "encloses"
    case fullyInside = "fullyInside"
    case overlaps = "overlaps"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var type: OneOf_Type? = nil
    let typeCheckAndSet = {
      if type != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'type'"
          ))
      }
      type = $0
    }
    if let encloses = try container.decodeIfPresent(Encloses?.self, forKey: .encloses) {
      try typeCheckAndSet(.encloses(encloses))
    }
    if let fullyInside = try container.decodeIfPresent(FullyInside?.self, forKey: .fullyInside) {
      try typeCheckAndSet(.fullyInside(fullyInside))
    }
    if let overlaps = try container.decodeIfPresent(Overlap?.self, forKey: .overlaps) {
      try typeCheckAndSet(.overlaps(overlaps))
    }
    self.type = type
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.type {
      switch choice {
      case .encloses(let value):
        try container.encode(value, forKey: .encloses)
      case .fullyInside(let value):
        try container.encode(value, forKey: .fullyInside)
      case .overlaps(let value):
        try container.encode(value, forKey: .overlaps)
      }
    }
  }

  /// The type of relationship to check between the target finding and the
  /// context finding.
  public enum OneOf_Type: Codable, Equatable, Sendable {
    /// The context finding's bounding box must fully contain the target
    /// finding's bounding box.
    indirect case encloses(Encloses?)
    /// The context finding's bounding box must be fully inside the target
    /// finding's bounding box.
    indirect case fullyInside(FullyInside?)
    /// The context finding's bounding box and the target finding's bounding box
    /// must have a non-zero intersection.
    indirect case overlaps(Overlap?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.ImageContainmentType"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
