// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The results of an inspect DataSource job.
public struct InspectDataSourceDetails: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The configuration used for this job.
  public var requestedOptions: InspectDataSourceDetails.RequestedOptions? = nil

  /// Output only. A summary of the outcome of this inspection job.
  public var result: InspectDataSourceDetails.Result? = nil

  /// Initialize a new instance of `InspectDataSourceDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InspectDataSourceDetails().with { $0.requestedOptions = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Snapshot of the inspection configuration.
  public struct RequestedOptions: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Output only. If run with an InspectTemplate, a snapshot of its state at
    /// the time of this run.
    public var snapshotInspectTemplate: InspectTemplate? = nil

    /// Inspect config.
    public var jobConfig: InspectJobConfig? = nil

    /// Initialize a new instance of `RequestedOptions`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RequestedOptions().with { $0.snapshotInspectTemplate = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.InspectDataSourceDetails.RequestedOptions"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// All Result fields are updated while the job is processing.
  public struct Result: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Total size in bytes that were processed.
    public var processedBytes: Swift.Int64 = Swift.Int64()

    /// Estimate of the number of bytes to process.
    public var totalEstimatedBytes: Swift.Int64 = Swift.Int64()

    /// Statistics of how many instances of each info type were found during
    /// inspect job.
    public var infoTypeStats: [InfoTypeStats] = []

    /// Number of rows scanned after sampling and time filtering (applicable for
    /// row based stores such as BigQuery).
    public var numRowsProcessed: Swift.Int64 = Swift.Int64()

    /// Statistics related to the processing of hybrid inspect.
    public var hybridStats: HybridInspectStatistics? = nil

    /// Initialize a new instance of `Result`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Result().with { $0.processedBytes = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.InspectDataSourceDetails.Result"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.InspectDataSourceDetails"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
