// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request message for ListConnections.
public struct ListConnectionsRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Resource name of the organization or project, for
  /// example, `organizations/433245324/locations/europe` or
  /// `projects/project-id/locations/asia`.
  public var parent: Swift.String = Swift.String()

  /// Optional. Number of results per page, max 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. Page token from a previous page to return the next set of
  /// results. If set, all other request fields must match the original request.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. Supported field/value: `state` - MISSING|AVAILABLE|ERROR
  ///
  /// The syntax is based on https://google.aip.dev/160.
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `ListConnectionsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListConnectionsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.ListConnectionsRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
