// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request to list the profiles generated for a given organization or project.
public struct ListTableDataProfilesRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Resource name of the organization or project, for
  /// example `organizations/433245324/locations/europe` or
  /// `projects/project-id/locations/asia`.
  public var parent: Swift.String = Swift.String()

  /// Page token to continue retrieval.
  public var pageToken: Swift.String = Swift.String()

  /// Size of the page. This value can be limited by the server. If zero, server
  /// returns a page of max size 100.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Comma-separated list of fields to order by, followed by `asc` or `desc`
  /// postfix. This list is case insensitive. The default sorting order is
  /// ascending. Redundant space characters are insignificant. Only one order
  /// field at a time is allowed.
  ///
  /// Examples:
  /// * `project_id asc`
  /// * `table_id`
  /// * `sensitivity_level desc`
  ///
  /// Supported fields are:
  ///
  /// - `project_id`: The Google Cloud project ID.
  /// - `dataset_id`: The ID of a BigQuery dataset.
  /// - `table_id`: The ID of a BigQuery table.
  /// - `sensitivity_level`: How sensitive the data in a table is, at most.
  /// - `data_risk_level`: How much risk is associated with this data.
  /// - `profile_last_generated`: When the profile was last updated in epoch
  /// seconds.
  /// - `last_modified`: The last time the resource was modified.
  /// - `resource_visibility`: Visibility restriction for this resource.
  /// - `row_count`: Number of rows in this resource.
  public var orderBy: Swift.String = Swift.String()

  /// Allows filtering.
  ///
  /// Supported syntax:
  ///
  /// * Filter expressions are made up of one or more restrictions.
  /// * Restrictions can be combined by `AND` or `OR` logical operators. A
  /// sequence of restrictions implicitly uses `AND`.
  /// * A restriction has the form of `{field} {operator} {value}`.
  /// * Supported fields:
  ///     - `project_id`: The Google Cloud project ID
  ///     - `dataset_id`: The BigQuery dataset ID
  ///     - `table_id`: The ID of the BigQuery table
  ///     - `sensitivity_level`: HIGH|MODERATE|LOW
  ///     - `data_risk_level`: HIGH|MODERATE|LOW
  ///     - `resource_visibility`: PUBLIC|RESTRICTED
  ///     - `status_code`: an RPC status code as defined in
  ///     https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto
  ///     - `profile_last_generated`: Date and time the profile was last
  ///       generated
  ///
  /// * The operator must be `=` or `!=`. The `profile_last_generated` filter
  ///   also supports `<` and `>`.
  ///
  /// The syntax is based on https://google.aip.dev/160.
  ///
  /// Examples:
  ///
  /// * `project_id = 12345 AND status_code = 1`
  /// * `project_id = 12345 AND sensitivity_level = HIGH`
  /// * `project_id = 12345 AND resource_visibility = PUBLIC`
  /// * `profile_last_generated < "2025-01-01T00:00:00.000Z"`
  ///
  /// The length of this field should be no more than 500 characters.
  public var filter: Swift.String = Swift.String()

  /// Initialize a new instance of `ListTableDataProfilesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListTableDataProfilesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.ListTableDataProfilesRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
