// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The other cloud starting location for discovery.
public struct OtherCloudDiscoveryStartingLocation: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The other cloud starting location for discovery.
  public var location: OneOf_Location? = nil

  /// Initialize a new instance of `OtherCloudDiscoveryStartingLocation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OtherCloudDiscoveryStartingLocation().with { $0.awsLocation = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case awsLocation = "awsLocation"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var location: OneOf_Location? = nil
    let locationCheckAndSet = {
      if location != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'location'"))
      }
      location = $0
    }
    if let awsLocation = try container.decodeIfPresent(
      OtherCloudDiscoveryStartingLocation.AwsDiscoveryStartingLocation?.self, forKey: .awsLocation)
    {
      try locationCheckAndSet(.awsLocation(awsLocation))
    }
    self.location = location
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.location {
      switch choice {
      case .awsLocation(let value):
        try container.encode(value, forKey: .awsLocation)
      }
    }
  }

  /// The AWS starting location for discovery.
  public struct AwsDiscoveryStartingLocation: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The scope of this starting location.
    public var scope: OneOf_Scope? = nil

    /// Initialize a new instance of `AwsDiscoveryStartingLocation`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AwsDiscoveryStartingLocation().with { $0.accountId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case accountId = "accountId"
      case allAssetInventoryAssets = "allAssetInventoryAssets"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var scope: OneOf_Scope? = nil
      let scopeCheckAndSet = {
        if scope != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'scope'"))
        }
        scope = $0
      }
      if let accountId = try container.decodeIfPresent(Swift.String.self, forKey: .accountId) {
        try scopeCheckAndSet(.accountId(accountId))
      }
      if let allAssetInventoryAssets = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .allAssetInventoryAssets)
      {
        try scopeCheckAndSet(.allAssetInventoryAssets(allAssetInventoryAssets))
      }
      self.scope = scope
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.scope {
        switch choice {
        case .accountId(let value):
          try container.encode(value, forKey: .accountId)
        case .allAssetInventoryAssets(let value):
          try container.encode(value, forKey: .allAssetInventoryAssets)
        }
      }
    }

    /// The scope of this starting location.
    public enum OneOf_Scope: Codable, Equatable, Sendable {
      /// The AWS account ID that this discovery config applies to.
      /// Within an AWS organization, you can find the AWS account ID inside an
      /// AWS account ARN. Example:
      /// arn:{partition}:organizations::{management_account_id}:account/{org_id}/{account_id}
      case accountId(Swift.String)
      /// All AWS assets stored in Asset Inventory that didn't match other AWS
      /// discovery configs.
      case allAssetInventoryAssets(Swift.Bool)
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.privacy.dlp.v2.OtherCloudDiscoveryStartingLocation.AwsDiscoveryStartingLocation"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The other cloud starting location for discovery.
  public enum OneOf_Location: Codable, Equatable, Sendable {
    /// The AWS starting location for discovery.
    indirect case awsLocation(OtherCloudDiscoveryStartingLocation.AwsDiscoveryStartingLocation?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.OtherCloudDiscoveryStartingLocation"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
