// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Infotype details for other infoTypes found within a column.
public struct OtherInfoTypeSummary: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The other infoType.
  public var infoType: InfoType? = nil

  /// Approximate percentage of non-null rows that contained data detected by
  /// this infotype.
  public var estimatedPrevalence: Swift.Int32 = Swift.Int32()

  /// Whether this infoType was excluded from sensitivity and risk analysis due
  /// to factors such as low prevalence (subject to change).
  public var excludedFromAnalysis: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `OtherInfoTypeSummary`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OtherInfoTypeSummary().with { $0.infoType = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.OtherInfoTypeSummary"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
