// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Message for a unique key indicating a record that contains a finding.
public struct RecordKey: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Values of identifying columns in the given row. Order of values matches
  /// the order of `identifying_fields` specified in the scanning request.
  public var idValues: [Swift.String] = []

  /// Type of key
  public var type: OneOf_Type? = nil

  /// Initialize a new instance of `RecordKey`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RecordKey().with { $0.datastoreKey = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case datastoreKey = "datastoreKey"
    case bigQueryKey = "bigQueryKey"
    case idValues = "idValues"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.idValues = try container.decode([Swift.String].self, forKey: .idValues)

    var type: OneOf_Type? = nil
    let typeCheckAndSet = {
      if type != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'type'"
          ))
      }
      type = $0
    }
    if let datastoreKey = try container.decodeIfPresent(DatastoreKey?.self, forKey: .datastoreKey) {
      try typeCheckAndSet(.datastoreKey(datastoreKey))
    }
    if let bigQueryKey = try container.decodeIfPresent(BigQueryKey?.self, forKey: .bigQueryKey) {
      try typeCheckAndSet(.bigQueryKey(bigQueryKey))
    }
    self.type = type
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.idValues, forKey: .idValues)

    if let choice = self.type {
      switch choice {
      case .datastoreKey(let value):
        try container.encode(value, forKey: .datastoreKey)
      case .bigQueryKey(let value):
        try container.encode(value, forKey: .bigQueryKey)
      }
    }
  }

  /// Type of key
  public enum OneOf_Type: Codable, Equatable, Sendable {
    /// BigQuery key
    indirect case datastoreKey(DatastoreKey?)
    /// Datastore key
    indirect case bigQueryKey(BigQueryKey?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.RecordKey"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
