// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Replace each input value with a value randomly selected from the dictionary.
public struct ReplaceDictionaryConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Type of dictionary.
  public var type: OneOf_Type? = nil

  /// Initialize a new instance of `ReplaceDictionaryConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReplaceDictionaryConfig().with { $0.wordList = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case wordList = "wordList"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var type: OneOf_Type? = nil
    let typeCheckAndSet = {
      if type != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'type'"
          ))
      }
      type = $0
    }
    if let wordList = try container.decodeIfPresent(
      CustomInfoType.Dictionary.WordList?.self, forKey: .wordList)
    {
      try typeCheckAndSet(.wordList(wordList))
    }
    self.type = type
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.type {
      switch choice {
      case .wordList(let value):
        try container.encode(value, forKey: .wordList)
      }
    }
  }

  /// Type of dictionary.
  public enum OneOf_Type: Codable, Equatable, Sendable {
    /// A list of words to select from for random replacement. The
    /// [limits](https://cloud.google.com/sensitive-data-protection/limits) page
    /// contains details about the size limits of dictionaries.
    indirect case wordList(CustomInfoType.Dictionary.WordList?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.ReplaceDictionaryConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
