// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A tag associated with a resource.
public struct Tag: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The namespaced name for the tag value to attach to Google Cloud resources.
  /// Must be in the format `{parent_id}/{tag_key_short_name}/{short_name}`, for
  /// example, "123456/environment/prod" for an organization parent, or
  /// "my-project/environment/prod" for a project parent. This is only set for
  /// Google Cloud resources.
  public var namespacedTagValue: Swift.String = Swift.String()

  /// The key of a tag key-value pair. For Google Cloud resources, this is the
  /// resource name of the key, for example, "tagKeys/123456".
  public var key: Swift.String = Swift.String()

  /// The value of a tag key-value pair. For Google Cloud resources, this is the
  /// resource name of the value, for example, "tagValues/123456".
  public var value: Swift.String = Swift.String()

  /// Initialize a new instance of `Tag`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Tag().with { $0.namespacedTagValue = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.Tag"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
