// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Details about a single transformation. This object contains a description of
/// the transformation, information about whether the transformation was
/// successfully applied, and the precise location where the transformation
/// occurred. These details are stored in a user-specified BigQuery table.
public struct TransformationDetails: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The name of the job that completed the transformation.
  public var resourceName: Swift.String = Swift.String()

  /// The top level name of the container where the transformation is located
  /// (this will be the source file name or table name).
  public var containerName: Swift.String = Swift.String()

  /// Description of transformation. This would only contain more than one
  /// element if there were multiple matching transformations and which one to
  /// apply was ambiguous. Not set for states that contain no transformation,
  /// currently only state that contains no transformation is
  /// TransformationResultStateType.METADATA_UNRETRIEVABLE.
  public var transformation: [TransformationDescription] = []

  /// Status of the transformation, if transformation was not successful, this
  /// will specify what caused it to fail, otherwise it will show that the
  /// transformation was successful.
  public var statusDetails: TransformationResultStatus? = nil

  /// The number of bytes that were transformed. If transformation was
  /// unsuccessful or did not take place because there was no content to
  /// transform, this will be zero.
  public var transformedBytes: Swift.Int64 = Swift.Int64()

  /// The precise location of the transformed content in the original container.
  public var transformationLocation: TransformationLocation? = nil

  /// Initialize a new instance of `TransformationDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransformationDetails().with { $0.resourceName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.TransformationDetails"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
