// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Target used to match against for discovery with Cloud Storage buckets.
public struct CloudStorageDiscoveryTarget: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The buckets the generation_cadence applies to. The first target
  /// with a matching filter will be the one to apply to a bucket.
  public var filter: DiscoveryCloudStorageFilter? = nil

  /// Optional. In addition to matching the filter, these conditions must be true
  /// before a profile is generated.
  public var conditions: DiscoveryFileStoreConditions? = nil

  /// How often and when to update profiles.
  public var cadence: OneOf_Cadence? = nil

  /// Initialize a new instance of `CloudStorageDiscoveryTarget`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudStorageDiscoveryTarget().with { $0.filter = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: String, CodingKey {
    case filter = "filter"
    case conditions = "conditions"
    case generationCadence = "generationCadence"
    case disabled = "disabled"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.filter = try container.decodeIfPresent(DiscoveryCloudStorageFilter.self, forKey: .filter)
    self.conditions = try container.decodeIfPresent(
      DiscoveryFileStoreConditions.self, forKey: .conditions)

    var cadence: OneOf_Cadence? = nil
    let cadenceCheckAndSet = {
      if cadence != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'cadence'"))
      }
      cadence = $0
    }
    if let generationCadence = try container.decodeIfPresent(
      DiscoveryCloudStorageGenerationCadence?.self, forKey: .generationCadence)
    {
      try cadenceCheckAndSet(.generationCadence(generationCadence))
    }
    if let disabled = try container.decodeIfPresent(Disabled?.self, forKey: .disabled) {
      try cadenceCheckAndSet(.disabled(disabled))
    }
    self.cadence = cadence
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.filter, forKey: .filter)
    try container.encode(self.conditions, forKey: .conditions)

    if let choice = self.cadence {
      switch choice {
      case .generationCadence(let value):
        try container.encode(value, forKey: .generationCadence)
      case .disabled(let value):
        try container.encode(value, forKey: .disabled)
      }
    }
  }

  /// How often and when to update profiles.
  public enum OneOf_Cadence: Codable, Equatable, Sendable {
    /// Optional. How often and when to update profiles. New buckets that match
    /// both the filter and conditions are scanned as quickly as possible
    /// depending on system capacity.
    indirect case generationCadence(DiscoveryCloudStorageGenerationCadence?)
    /// Optional. Disable profiling for buckets that match this filter.
    indirect case disabled(Disabled?)
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.privacy.dlp.v2.CloudStorageDiscoveryTarget"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
