// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Type of content to inspect.
public struct ContentItem: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// User provided metadata for the content.
  public var contentMetadata: ContentMetadata? = nil

  /// Data of the item either in the byte array or UTF-8 string form, or table.
  public var dataItem: OneOf_DataItem? = nil

  /// Initialize a new instance of `ContentItem`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ContentItem().with { $0.value = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case value = "value"
    case table = "table"
    case byteItem = "byteItem"
    case conversation = "conversation"
    case contentMetadata = "contentMetadata"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.contentMetadata = try container.decodeIfPresent(
      ContentMetadata.self, forKey: .contentMetadata)

    var dataItem: OneOf_DataItem? = nil
    let dataItemCheckAndSet = {
      if dataItem != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'dataItem'"))
      }
      dataItem = $0
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .value) {
      try dataItemCheckAndSet(.value(value))
    }
    if let table = try container.decodeIfPresent(Table?.self, forKey: .table) {
      try dataItemCheckAndSet(.table(table))
    }
    if let byteItem = try container.decodeIfPresent(ByteContentItem?.self, forKey: .byteItem) {
      try dataItemCheckAndSet(.byteItem(byteItem))
    }
    if let conversation = try container.decodeIfPresent(Conversation?.self, forKey: .conversation) {
      try dataItemCheckAndSet(.conversation(conversation))
    }
    self.dataItem = dataItem
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.contentMetadata, forKey: .contentMetadata)

    if let choice = self.dataItem {
      switch choice {
      case .value(let value):
        try container.encode(value, forKey: .value)
      case .table(let value):
        try container.encode(value, forKey: .table)
      case .byteItem(let value):
        try container.encode(value, forKey: .byteItem)
      case .conversation(let value):
        try container.encode(value, forKey: .conversation)
      }
    }
  }

  /// Data of the item either in the byte array or UTF-8 string form, or table.
  public enum OneOf_DataItem: Codable, Equatable, Sendable {
    /// String data to inspect or redact.
    case value(Swift.String)
    /// Structured content for inspection. See
    /// https://cloud.google.com/sensitive-data-protection/docs/inspecting-text#inspecting_a_table
    /// to learn more.
    indirect case table(Table?)
    /// Content data to inspect or redact. Replaces `type` and `data`.
    indirect case byteItem(ByteContentItem?)
    /// Represents a conversation (either complete or a slice).
    /// It is assumed that all included messages are contiguous and ordered in
    /// chronological order.
    indirect case conversation(Conversation?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.ContentItem"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
