// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The data that will be profiled.
public struct DataProfileLocation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The location to be scanned.
  public var location: OneOf_Location? = nil

  /// Initialize a new instance of `DataProfileLocation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataProfileLocation().with { $0.organizationId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case organizationId = "organizationId"
    case folderId = "folderId"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var location: OneOf_Location? = nil
    let locationCheckAndSet = {
      if location != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'location'"))
      }
      location = $0
    }
    if let organizationId = try container.decodeIfPresent(Swift.Int64.self, forKey: .organizationId)
    {
      try locationCheckAndSet(.organizationId(organizationId))
    }
    if let folderId = try container.decodeIfPresent(Swift.Int64.self, forKey: .folderId) {
      try locationCheckAndSet(.folderId(folderId))
    }
    self.location = location
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.location {
      switch choice {
      case .organizationId(let value):
        try container.encode(value, forKey: .organizationId)
      case .folderId(let value):
        try container.encode(value, forKey: .folderId)
      }
    }
  }

  /// The location to be scanned.
  public enum OneOf_Location: Codable, Equatable, Sendable {
    /// The ID of an organization to scan.
    case organizationId(Swift.Int64)
    /// The ID of the folder within an organization to scan.
    case folderId(Swift.Int64)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.DataProfileLocation"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
