// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Location of a data profile finding within a resource.
public struct DataProfileFindingLocation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Name of the container where the finding is located.
  /// The top-level name is the source file name or table name. Names of some
  /// common storage containers are formatted as follows:
  ///
  /// * BigQuery tables:  `{project_id}:{dataset_id}.{table_id}`
  /// * Cloud Storage files: `gs://{bucket}/{path}`
  public var containerName: Swift.String = Swift.String()

  /// Additional location details that may be provided for some types of
  /// profiles. At this time, only findings for table data profiles include such
  /// details.
  public var locationExtraDetails: OneOf_LocationExtraDetails? = nil

  /// Initialize a new instance of `DataProfileFindingLocation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DataProfileFindingLocation().with { $0.containerName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: String, CodingKey {
    case containerName = "containerName"
    case dataProfileFindingRecordLocation = "dataProfileFindingRecordLocation"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.containerName = try container.decode(Swift.String.self, forKey: .containerName)

    var locationExtraDetails: OneOf_LocationExtraDetails? = nil
    let locationExtraDetailsCheckAndSet = {
      if locationExtraDetails != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'locationExtraDetails'"))
      }
      locationExtraDetails = $0
    }
    if let dataProfileFindingRecordLocation = try container.decodeIfPresent(
      DataProfileFindingRecordLocation?.self, forKey: .dataProfileFindingRecordLocation)
    {
      try locationExtraDetailsCheckAndSet(
        .dataProfileFindingRecordLocation(dataProfileFindingRecordLocation))
    }
    self.locationExtraDetails = locationExtraDetails
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.containerName, forKey: .containerName)

    if let choice = self.locationExtraDetails {
      switch choice {
      case .dataProfileFindingRecordLocation(let value):
        try container.encode(value, forKey: .dataProfileFindingRecordLocation)
      }
    }
  }

  /// Additional location details that may be provided for some types of
  /// profiles. At this time, only findings for table data profiles include such
  /// details.
  public enum OneOf_LocationExtraDetails: Codable, Equatable, Sendable {
    /// Location of a finding within a resource that produces a table data
    /// profile.
    indirect case dataProfileFindingRecordLocation(DataProfileFindingRecordLocation?)
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.privacy.dlp.v2.DataProfileFindingLocation"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
