// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Determines what tables will have profiles generated within an organization
/// or project. Includes the ability to filter by regular expression patterns
/// on project ID, location, instance, database, and database resource name.
public struct DiscoveryCloudSqlFilter: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Whether the filter applies to a specific set of database resources or all
  /// other database resources within the location being profiled. The first
  /// filter to match will be applied, regardless of the condition. If none is
  /// set, will default to `others`.
  public var filter: OneOf_Filter? = nil

  /// Initialize a new instance of `DiscoveryCloudSqlFilter`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DiscoveryCloudSqlFilter().with { $0.collection = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case collection = "collection"
    case others = "others"
    case databaseResourceReference = "databaseResourceReference"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var filter: OneOf_Filter? = nil
    let filterCheckAndSet = {
      if filter != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'filter'"))
      }
      filter = $0
    }
    if let collection = try container.decodeIfPresent(
      DatabaseResourceCollection?.self, forKey: .collection)
    {
      try filterCheckAndSet(.collection(collection))
    }
    if let others = try container.decodeIfPresent(AllOtherDatabaseResources?.self, forKey: .others)
    {
      try filterCheckAndSet(.others(others))
    }
    if let databaseResourceReference = try container.decodeIfPresent(
      DatabaseResourceReference?.self, forKey: .databaseResourceReference)
    {
      try filterCheckAndSet(.databaseResourceReference(databaseResourceReference))
    }
    self.filter = filter
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.filter {
      switch choice {
      case .collection(let value):
        try container.encode(value, forKey: .collection)
      case .others(let value):
        try container.encode(value, forKey: .others)
      case .databaseResourceReference(let value):
        try container.encode(value, forKey: .databaseResourceReference)
      }
    }
  }

  /// Whether the filter applies to a specific set of database resources or all
  /// other database resources within the location being profiled. The first
  /// filter to match will be applied, regardless of the condition. If none is
  /// set, will default to `others`.
  public enum OneOf_Filter: Codable, Equatable, Sendable {
    /// A specific set of database resources for this filter to apply to.
    indirect case collection(DatabaseResourceCollection?)
    /// Catch-all. This should always be the last target in the list because
    /// anything above it will apply first. Should only appear once in a
    /// configuration. If none is specified, a default one will be added
    /// automatically.
    indirect case others(AllOtherDatabaseResources?)
    /// The database resource to scan. Targets including this can only include
    /// one target (the target with this database resource reference).
    indirect case databaseResourceReference(DatabaseResourceReference?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.DiscoveryCloudSqlFilter"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
