// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class DlpServiceLogging: DlpServiceStub {
    let inner: any DlpServiceStub
    let logger: Logger

    public init(_ inner: any DlpServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "GooglePrivacyDlpV2"
      logger[metadataKey: "gcp.client.service"] = "dlp"
      logger[metadataKey: "gcp.experimental.swift.client"] = "DlpService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func inspectContent(
      request: InspectContentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.InspectContentResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "inspectContent",
        action: {
          (r: InspectContentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.InspectContentResponse
          in
          return try await self.inner.inspectContent(request: r, options: o)
        })
    }

    public func redactImage(
      request: RedactImageRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.RedactImageResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "redactImage",
        action: {
          (r: RedactImageRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.RedactImageResponse
          in
          return try await self.inner.redactImage(request: r, options: o)
        })
    }

    public func deidentifyContent(
      request: DeidentifyContentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.DeidentifyContentResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "deidentifyContent",
        action: {
          (r: DeidentifyContentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.DeidentifyContentResponse
          in
          return try await self.inner.deidentifyContent(request: r, options: o)
        })
    }

    public func reidentifyContent(
      request: ReidentifyContentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.ReidentifyContentResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "reidentifyContent",
        action: {
          (r: ReidentifyContentRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.ReidentifyContentResponse
          in
          return try await self.inner.reidentifyContent(request: r, options: o)
        })
    }

    public func listInfoTypes(
      request: ListInfoTypesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.ListInfoTypesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listInfoTypes",
        action: {
          (r: ListInfoTypesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.ListInfoTypesResponse
          in
          return try await self.inner.listInfoTypes(request: r, options: o)
        })
    }

    public func createInspectTemplate(
      request: CreateInspectTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.InspectTemplate {
      try await self._intercept(
        request: request,
        options: options,
        name: "createInspectTemplate",
        action: {
          (r: CreateInspectTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.InspectTemplate
          in
          return try await self.inner.createInspectTemplate(request: r, options: o)
        })
    }

    public func updateInspectTemplate(
      request: UpdateInspectTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.InspectTemplate {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateInspectTemplate",
        action: {
          (r: UpdateInspectTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.InspectTemplate
          in
          return try await self.inner.updateInspectTemplate(request: r, options: o)
        })
    }

    public func getInspectTemplate(
      request: GetInspectTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.InspectTemplate {
      try await self._intercept(
        request: request,
        options: options,
        name: "getInspectTemplate",
        action: {
          (r: GetInspectTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.InspectTemplate
          in
          return try await self.inner.getInspectTemplate(request: r, options: o)
        })
    }

    public func listInspectTemplates(
      request: ListInspectTemplatesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.ListInspectTemplatesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listInspectTemplates",
        action: {
          (r: ListInspectTemplatesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.ListInspectTemplatesResponse
          in
          return try await self.inner.listInspectTemplates(request: r, options: o)
        })
    }

    public func deleteInspectTemplate(
      request: DeleteInspectTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteInspectTemplate",
        action: {
          (r: DeleteInspectTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void
          in
          return try await self.inner.deleteInspectTemplate(request: r, options: o)
        })
    }

    public func createDeidentifyTemplate(
      request: CreateDeidentifyTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.DeidentifyTemplate {
      try await self._intercept(
        request: request,
        options: options,
        name: "createDeidentifyTemplate",
        action: {
          (r: CreateDeidentifyTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.DeidentifyTemplate
          in
          return try await self.inner.createDeidentifyTemplate(request: r, options: o)
        })
    }

    public func updateDeidentifyTemplate(
      request: UpdateDeidentifyTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.DeidentifyTemplate {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateDeidentifyTemplate",
        action: {
          (r: UpdateDeidentifyTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.DeidentifyTemplate
          in
          return try await self.inner.updateDeidentifyTemplate(request: r, options: o)
        })
    }

    public func getDeidentifyTemplate(
      request: GetDeidentifyTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.DeidentifyTemplate {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDeidentifyTemplate",
        action: {
          (r: GetDeidentifyTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.DeidentifyTemplate
          in
          return try await self.inner.getDeidentifyTemplate(request: r, options: o)
        })
    }

    public func listDeidentifyTemplates(
      request: ListDeidentifyTemplatesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.ListDeidentifyTemplatesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDeidentifyTemplates",
        action: {
          (r: ListDeidentifyTemplatesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.ListDeidentifyTemplatesResponse
          in
          return try await self.inner.listDeidentifyTemplates(request: r, options: o)
        })
    }

    public func deleteDeidentifyTemplate(
      request: DeleteDeidentifyTemplateRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteDeidentifyTemplate",
        action: {
          (r: DeleteDeidentifyTemplateRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteDeidentifyTemplate(request: r, options: o)
        })
    }

    public func createJobTrigger(
      request: CreateJobTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.JobTrigger {
      try await self._intercept(
        request: request,
        options: options,
        name: "createJobTrigger",
        action: {
          (r: CreateJobTriggerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.JobTrigger
          in
          return try await self.inner.createJobTrigger(request: r, options: o)
        })
    }

    public func updateJobTrigger(
      request: UpdateJobTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.JobTrigger {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateJobTrigger",
        action: {
          (r: UpdateJobTriggerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.JobTrigger
          in
          return try await self.inner.updateJobTrigger(request: r, options: o)
        })
    }

    public func hybridInspectJobTrigger(
      request: HybridInspectJobTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.HybridInspectResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "hybridInspectJobTrigger",
        action: {
          (r: HybridInspectJobTriggerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.HybridInspectResponse
          in
          return try await self.inner.hybridInspectJobTrigger(request: r, options: o)
        })
    }

    public func getJobTrigger(
      request: GetJobTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.JobTrigger {
      try await self._intercept(
        request: request,
        options: options,
        name: "getJobTrigger",
        action: {
          (r: GetJobTriggerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.JobTrigger
          in
          return try await self.inner.getJobTrigger(request: r, options: o)
        })
    }

    public func listJobTriggers(
      request: ListJobTriggersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.ListJobTriggersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listJobTriggers",
        action: {
          (r: ListJobTriggersRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.ListJobTriggersResponse
          in
          return try await self.inner.listJobTriggers(request: r, options: o)
        })
    }

    public func deleteJobTrigger(
      request: DeleteJobTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteJobTrigger",
        action: {
          (r: DeleteJobTriggerRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteJobTrigger(request: r, options: o)
        })
    }

    public func activateJobTrigger(
      request: ActivateJobTriggerRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.DlpJob {
      try await self._intercept(
        request: request,
        options: options,
        name: "activateJobTrigger",
        action: {
          (r: ActivateJobTriggerRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.DlpJob
          in
          return try await self.inner.activateJobTrigger(request: r, options: o)
        })
    }

    public func createDiscoveryConfig(
      request: CreateDiscoveryConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.DiscoveryConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "createDiscoveryConfig",
        action: {
          (r: CreateDiscoveryConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.DiscoveryConfig
          in
          return try await self.inner.createDiscoveryConfig(request: r, options: o)
        })
    }

    public func updateDiscoveryConfig(
      request: UpdateDiscoveryConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.DiscoveryConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateDiscoveryConfig",
        action: {
          (r: UpdateDiscoveryConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.DiscoveryConfig
          in
          return try await self.inner.updateDiscoveryConfig(request: r, options: o)
        })
    }

    public func getDiscoveryConfig(
      request: GetDiscoveryConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.DiscoveryConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDiscoveryConfig",
        action: {
          (r: GetDiscoveryConfigRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.DiscoveryConfig
          in
          return try await self.inner.getDiscoveryConfig(request: r, options: o)
        })
    }

    public func listDiscoveryConfigs(
      request: ListDiscoveryConfigsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.ListDiscoveryConfigsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDiscoveryConfigs",
        action: {
          (r: ListDiscoveryConfigsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.ListDiscoveryConfigsResponse
          in
          return try await self.inner.listDiscoveryConfigs(request: r, options: o)
        })
    }

    public func deleteDiscoveryConfig(
      request: DeleteDiscoveryConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteDiscoveryConfig",
        action: {
          (r: DeleteDiscoveryConfigRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void
          in
          return try await self.inner.deleteDiscoveryConfig(request: r, options: o)
        })
    }

    public func createDlpJob(
      request: CreateDlpJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.DlpJob {
      try await self._intercept(
        request: request,
        options: options,
        name: "createDlpJob",
        action: {
          (r: CreateDlpJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.DlpJob
          in
          return try await self.inner.createDlpJob(request: r, options: o)
        })
    }

    public func listDlpJobs(
      request: ListDlpJobsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.ListDlpJobsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDlpJobs",
        action: {
          (r: ListDlpJobsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.ListDlpJobsResponse
          in
          return try await self.inner.listDlpJobs(request: r, options: o)
        })
    }

    public func getDlpJob(
      request: GetDlpJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.DlpJob {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDlpJob",
        action: {
          (r: GetDlpJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.DlpJob
          in
          return try await self.inner.getDlpJob(request: r, options: o)
        })
    }

    public func deleteDlpJob(
      request: DeleteDlpJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteDlpJob",
        action: { (r: DeleteDlpJobRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteDlpJob(request: r, options: o)
        })
    }

    public func cancelDlpJob(
      request: CancelDlpJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelDlpJob",
        action: { (r: CancelDlpJobRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.cancelDlpJob(request: r, options: o)
        })
    }

    public func createStoredInfoType(
      request: CreateStoredInfoTypeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.StoredInfoType {
      try await self._intercept(
        request: request,
        options: options,
        name: "createStoredInfoType",
        action: {
          (r: CreateStoredInfoTypeRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.StoredInfoType
          in
          return try await self.inner.createStoredInfoType(request: r, options: o)
        })
    }

    public func updateStoredInfoType(
      request: UpdateStoredInfoTypeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.StoredInfoType {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateStoredInfoType",
        action: {
          (r: UpdateStoredInfoTypeRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.StoredInfoType
          in
          return try await self.inner.updateStoredInfoType(request: r, options: o)
        })
    }

    public func getStoredInfoType(
      request: GetStoredInfoTypeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.StoredInfoType {
      try await self._intercept(
        request: request,
        options: options,
        name: "getStoredInfoType",
        action: {
          (r: GetStoredInfoTypeRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.StoredInfoType
          in
          return try await self.inner.getStoredInfoType(request: r, options: o)
        })
    }

    public func listStoredInfoTypes(
      request: ListStoredInfoTypesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.ListStoredInfoTypesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listStoredInfoTypes",
        action: {
          (r: ListStoredInfoTypesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.ListStoredInfoTypesResponse
          in
          return try await self.inner.listStoredInfoTypes(request: r, options: o)
        })
    }

    public func deleteStoredInfoType(
      request: DeleteStoredInfoTypeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteStoredInfoType",
        action: {
          (r: DeleteStoredInfoTypeRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteStoredInfoType(request: r, options: o)
        })
    }

    public func listProjectDataProfiles(
      request: ListProjectDataProfilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.ListProjectDataProfilesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listProjectDataProfiles",
        action: {
          (r: ListProjectDataProfilesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.ListProjectDataProfilesResponse
          in
          return try await self.inner.listProjectDataProfiles(request: r, options: o)
        })
    }

    public func listTableDataProfiles(
      request: ListTableDataProfilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.ListTableDataProfilesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTableDataProfiles",
        action: {
          (r: ListTableDataProfilesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.ListTableDataProfilesResponse
          in
          return try await self.inner.listTableDataProfiles(request: r, options: o)
        })
    }

    public func listColumnDataProfiles(
      request: ListColumnDataProfilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.ListColumnDataProfilesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listColumnDataProfiles",
        action: {
          (r: ListColumnDataProfilesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.ListColumnDataProfilesResponse
          in
          return try await self.inner.listColumnDataProfiles(request: r, options: o)
        })
    }

    public func getProjectDataProfile(
      request: GetProjectDataProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.ProjectDataProfile {
      try await self._intercept(
        request: request,
        options: options,
        name: "getProjectDataProfile",
        action: {
          (r: GetProjectDataProfileRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.ProjectDataProfile
          in
          return try await self.inner.getProjectDataProfile(request: r, options: o)
        })
    }

    public func listFileStoreDataProfiles(
      request: ListFileStoreDataProfilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.ListFileStoreDataProfilesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listFileStoreDataProfiles",
        action: {
          (r: ListFileStoreDataProfilesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.ListFileStoreDataProfilesResponse
          in
          return try await self.inner.listFileStoreDataProfiles(request: r, options: o)
        })
    }

    public func getFileStoreDataProfile(
      request: GetFileStoreDataProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.FileStoreDataProfile {
      try await self._intercept(
        request: request,
        options: options,
        name: "getFileStoreDataProfile",
        action: {
          (r: GetFileStoreDataProfileRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.FileStoreDataProfile
          in
          return try await self.inner.getFileStoreDataProfile(request: r, options: o)
        })
    }

    public func deleteFileStoreDataProfile(
      request: DeleteFileStoreDataProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteFileStoreDataProfile",
        action: {
          (r: DeleteFileStoreDataProfileRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteFileStoreDataProfile(request: r, options: o)
        })
    }

    public func getTableDataProfile(
      request: GetTableDataProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.TableDataProfile {
      try await self._intercept(
        request: request,
        options: options,
        name: "getTableDataProfile",
        action: {
          (r: GetTableDataProfileRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.TableDataProfile
          in
          return try await self.inner.getTableDataProfile(request: r, options: o)
        })
    }

    public func getColumnDataProfile(
      request: GetColumnDataProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.ColumnDataProfile {
      try await self._intercept(
        request: request,
        options: options,
        name: "getColumnDataProfile",
        action: {
          (r: GetColumnDataProfileRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.ColumnDataProfile
          in
          return try await self.inner.getColumnDataProfile(request: r, options: o)
        })
    }

    public func deleteTableDataProfile(
      request: DeleteTableDataProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteTableDataProfile",
        action: {
          (r: DeleteTableDataProfileRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void
          in
          return try await self.inner.deleteTableDataProfile(request: r, options: o)
        })
    }

    public func hybridInspectDlpJob(
      request: HybridInspectDlpJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.HybridInspectResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "hybridInspectDlpJob",
        action: {
          (r: HybridInspectDlpJobRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.HybridInspectResponse
          in
          return try await self.inner.hybridInspectDlpJob(request: r, options: o)
        })
    }

    public func finishDlpJob(
      request: FinishDlpJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "finishDlpJob",
        action: { (r: FinishDlpJobRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.finishDlpJob(request: r, options: o)
        })
    }

    public func createConnection(
      request: CreateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.Connection {
      try await self._intercept(
        request: request,
        options: options,
        name: "createConnection",
        action: {
          (r: CreateConnectionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.Connection
          in
          return try await self.inner.createConnection(request: r, options: o)
        })
    }

    public func getConnection(
      request: GetConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.Connection {
      try await self._intercept(
        request: request,
        options: options,
        name: "getConnection",
        action: {
          (r: GetConnectionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.Connection
          in
          return try await self.inner.getConnection(request: r, options: o)
        })
    }

    public func listConnections(
      request: ListConnectionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.ListConnectionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listConnections",
        action: {
          (r: ListConnectionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.ListConnectionsResponse
          in
          return try await self.inner.listConnections(request: r, options: o)
        })
    }

    public func searchConnections(
      request: SearchConnectionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.SearchConnectionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "searchConnections",
        action: {
          (r: SearchConnectionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.SearchConnectionsResponse
          in
          return try await self.inner.searchConnections(request: r, options: o)
        })
    }

    public func deleteConnection(
      request: DeleteConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteConnection",
        action: {
          (r: DeleteConnectionRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteConnection(request: r, options: o)
        })
    }

    public func updateConnection(
      request: UpdateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GooglePrivacyDlpV2.Connection {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateConnection",
        action: {
          (r: UpdateConnectionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GooglePrivacyDlpV2.Connection
          in
          return try await self.inner.updateConnection(request: r, options: o)
        })
    }
  }
}
