// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Statistics related to processing hybrid inspect requests.
public struct HybridInspectStatistics: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The number of hybrid inspection requests processed within this job.
  public var processedCount: Swift.Int64 = Swift.Int64()

  /// The number of hybrid inspection requests aborted because the job ran
  /// out of quota or was ended before they could be processed.
  public var abortedCount: Swift.Int64 = Swift.Int64()

  /// The number of hybrid requests currently being processed. Only populated
  /// when called via method `getDlpJob`.
  /// A burst of traffic may cause hybrid inspect requests to be enqueued.
  /// Processing will take place as quickly as possible, but resource limitations
  /// may impact how long a request is enqueued for.
  public var pendingCount: Swift.Int64 = Swift.Int64()

  /// Initialize a new instance of `HybridInspectStatistics`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = HybridInspectStatistics().with { $0.processedCount = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.privacy.dlp.v2.HybridInspectStatistics"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
