// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A single inspection rule to be applied to infoTypes, specified in
/// `InspectionRuleSet`.
public struct InspectionRule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Inspection rule types.
  public var type: OneOf_Type_? = nil

  /// Initialize a new instance of `InspectionRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = InspectionRule().with { $0.hotwordRule = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: String, CodingKey {
    case hotwordRule = "hotwordRule"
    case exclusionRule = "exclusionRule"
    case adjustmentRule = "adjustmentRule"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var type: OneOf_Type_? = nil
    let typeCheckAndSet = {
      if type != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'type'"
          ))
      }
      type = $0
    }
    if let hotwordRule = try container.decodeIfPresent(
      CustomInfoType.DetectionRule.HotwordRule?.self, forKey: .hotwordRule)
    {
      try typeCheckAndSet(.hotwordRule(hotwordRule))
    }
    if let exclusionRule = try container.decodeIfPresent(
      ExclusionRule?.self, forKey: .exclusionRule)
    {
      try typeCheckAndSet(.exclusionRule(exclusionRule))
    }
    if let adjustmentRule = try container.decodeIfPresent(
      AdjustmentRule?.self, forKey: .adjustmentRule)
    {
      try typeCheckAndSet(.adjustmentRule(adjustmentRule))
    }
    self.type = type
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.type {
      switch choice {
      case .hotwordRule(let value):
        try container.encode(value, forKey: .hotwordRule)
      case .exclusionRule(let value):
        try container.encode(value, forKey: .exclusionRule)
      case .adjustmentRule(let value):
        try container.encode(value, forKey: .adjustmentRule)
      }
    }
  }

  /// Inspection rule types.
  public enum OneOf_Type_: Codable, Equatable, Sendable {
    /// Hotword-based detection rule.
    indirect case hotwordRule(CustomInfoType.DetectionRule.HotwordRule?)
    /// Exclusion rule.
    indirect case exclusionRule(ExclusionRule?)
    /// Adjustment rule.
    indirect case adjustmentRule(AdjustmentRule?)
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.privacy.dlp.v2.InspectionRule"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
