// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Privacy metric to compute for reidentification risk analysis.
public struct PrivacyMetric: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Types of analysis.
  public var type: OneOf_Type_? = nil

  /// Initialize a new instance of `PrivacyMetric`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PrivacyMetric().with { $0.numericalStatsConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case numericalStatsConfig = "numericalStatsConfig"
    case categoricalStatsConfig = "categoricalStatsConfig"
    case kAnonymityConfig = "kAnonymityConfig"
    case lDiversityConfig = "lDiversityConfig"
    case kMapEstimationConfig = "kMapEstimationConfig"
    case deltaPresenceEstimationConfig = "deltaPresenceEstimationConfig"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var type: OneOf_Type_? = nil
    let typeCheckAndSet = {
      if type != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'type'"
          ))
      }
      type = $0
    }
    if let numericalStatsConfig = try container.decodeIfPresent(
      PrivacyMetric.NumericalStatsConfig?.self, forKey: .numericalStatsConfig)
    {
      try typeCheckAndSet(.numericalStatsConfig(numericalStatsConfig))
    }
    if let categoricalStatsConfig = try container.decodeIfPresent(
      PrivacyMetric.CategoricalStatsConfig?.self, forKey: .categoricalStatsConfig)
    {
      try typeCheckAndSet(.categoricalStatsConfig(categoricalStatsConfig))
    }
    if let kAnonymityConfig = try container.decodeIfPresent(
      PrivacyMetric.KAnonymityConfig?.self, forKey: .kAnonymityConfig)
    {
      try typeCheckAndSet(.kAnonymityConfig(kAnonymityConfig))
    }
    if let lDiversityConfig = try container.decodeIfPresent(
      PrivacyMetric.LDiversityConfig?.self, forKey: .lDiversityConfig)
    {
      try typeCheckAndSet(.lDiversityConfig(lDiversityConfig))
    }
    if let kMapEstimationConfig = try container.decodeIfPresent(
      PrivacyMetric.KMapEstimationConfig?.self, forKey: .kMapEstimationConfig)
    {
      try typeCheckAndSet(.kMapEstimationConfig(kMapEstimationConfig))
    }
    if let deltaPresenceEstimationConfig = try container.decodeIfPresent(
      PrivacyMetric.DeltaPresenceEstimationConfig?.self, forKey: .deltaPresenceEstimationConfig)
    {
      try typeCheckAndSet(.deltaPresenceEstimationConfig(deltaPresenceEstimationConfig))
    }
    self.type = type
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.type {
      switch choice {
      case .numericalStatsConfig(let value):
        try container.encode(value, forKey: .numericalStatsConfig)
      case .categoricalStatsConfig(let value):
        try container.encode(value, forKey: .categoricalStatsConfig)
      case .kAnonymityConfig(let value):
        try container.encode(value, forKey: .kAnonymityConfig)
      case .lDiversityConfig(let value):
        try container.encode(value, forKey: .lDiversityConfig)
      case .kMapEstimationConfig(let value):
        try container.encode(value, forKey: .kMapEstimationConfig)
      case .deltaPresenceEstimationConfig(let value):
        try container.encode(value, forKey: .deltaPresenceEstimationConfig)
      }
    }
  }

  /// Compute numerical stats over an individual column, including
  /// min, max, and quantiles.
  public struct NumericalStatsConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Field to compute numerical stats on. Supported types are
    /// integer, float, date, datetime, timestamp, time.
    public var field: FieldId? = nil

    /// Initialize a new instance of `NumericalStatsConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = NumericalStatsConfig().with { $0.field = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.PrivacyMetric.NumericalStatsConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Compute numerical stats over an individual column, including
  /// number of distinct values and value count distribution.
  public struct CategoricalStatsConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Field to compute categorical stats on. All column types are
    /// supported except for arrays and structs. However, it may be more
    /// informative to use NumericalStats when the field type is supported,
    /// depending on the data.
    public var field: FieldId? = nil

    /// Initialize a new instance of `CategoricalStatsConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CategoricalStatsConfig().with { $0.field = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.PrivacyMetric.CategoricalStatsConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// k-anonymity metric, used for analysis of reidentification risk.
  public struct KAnonymityConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Set of fields to compute k-anonymity over. When multiple fields are
    /// specified, they are considered a single composite key. Structs and
    /// repeated data types are not supported; however, nested fields are
    /// supported so long as they are not structs themselves or nested within
    /// a repeated field.
    public var quasiIds: [FieldId] = []

    /// Message indicating that multiple rows might be associated to a
    /// single individual. If the same entity_id is associated to multiple
    /// quasi-identifier tuples over distinct rows, we consider the entire
    /// collection of tuples as the composite quasi-identifier. This collection
    /// is a multiset: the order in which the different tuples appear in the
    /// dataset is ignored, but their frequency is taken into account.
    ///
    /// Important note: a maximum of 1000 rows can be associated to a single
    /// entity ID. If more rows are associated with the same entity ID, some
    /// might be ignored.
    public var entityId: EntityId? = nil

    /// Initialize a new instance of `KAnonymityConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = KAnonymityConfig().with { $0.quasiIds = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.PrivacyMetric.KAnonymityConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// l-diversity metric, used for analysis of reidentification risk.
  public struct LDiversityConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Set of quasi-identifiers indicating how equivalence classes are
    /// defined for the l-diversity computation. When multiple fields are
    /// specified, they are considered a single composite key.
    public var quasiIds: [FieldId] = []

    /// Sensitive field for computing the l-value.
    public var sensitiveAttribute: FieldId? = nil

    /// Initialize a new instance of `LDiversityConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LDiversityConfig().with { $0.quasiIds = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.PrivacyMetric.LDiversityConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Reidentifiability metric. This corresponds to a risk model similar to what
  /// is called "journalist risk" in the literature, except the attack dataset is
  /// statistically modeled instead of being perfectly known. This can be done
  /// using publicly available data (like the US Census), or using a custom
  /// statistical model (indicated as one or several BigQuery tables), or by
  /// extrapolating from the distribution of values in the input dataset.
  public struct KMapEstimationConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. Fields considered to be quasi-identifiers. No two columns can
    /// have the same tag.
    public var quasiIds: [PrivacyMetric.KMapEstimationConfig.TaggedField] = []

    /// ISO 3166-1 alpha-2 region code to use in the statistical modeling.
    /// Set if no column is tagged with a region-specific InfoType (like
    /// US_ZIP_5) or a region code.
    public var regionCode: Swift.String = Swift.String()

    /// Several auxiliary tables can be used in the analysis. Each custom_tag
    /// used to tag a quasi-identifiers column must appear in exactly one column
    /// of one auxiliary table.
    public var auxiliaryTables: [PrivacyMetric.KMapEstimationConfig.AuxiliaryTable] = []

    /// Initialize a new instance of `KMapEstimationConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = KMapEstimationConfig().with { $0.quasiIds = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// A column with a semantic tag attached.
    public struct TaggedField: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Required. Identifies the column.
      public var field: FieldId? = nil

      /// Semantic tag that identifies what a column contains, to determine which
      /// statistical model to use to estimate the reidentifiability of each
      /// value. [required]
      public var tag: OneOf_Tag? = nil

      /// Initialize a new instance of `TaggedField`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = TaggedField().with { $0.field = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private enum CodingKeys: Swift.String, CodingKey {
        case field = "field"
        case infoType = "infoType"
        case customTag = "customTag"
        case inferred = "inferred"
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.field = try container.decodeIfPresent(FieldId.self, forKey: .field)

        var tag: OneOf_Tag? = nil
        let tagCheckAndSet = {
          if tag != nil {
            throw DecodingError.dataCorrupted(
              DecodingError.Context(
                codingPath: decoder.codingPath,
                debugDescription: "Multiple values set for oneof 'tag'"))
          }
          tag = $0
        }
        if let infoType = try container.decodeIfPresent(InfoType?.self, forKey: .infoType) {
          try tagCheckAndSet(.infoType(infoType))
        }
        if let customTag = try container.decodeIfPresent(Swift.String.self, forKey: .customTag) {
          try tagCheckAndSet(.customTag(customTag))
        }
        if let inferred = try container.decodeIfPresent(
          GoogleCloudWkt.Empty?.self, forKey: .inferred)
        {
          try tagCheckAndSet(.inferred(inferred))
        }
        self.tag = tag
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.field, forKey: .field)

        if let choice = self.tag {
          switch choice {
          case .infoType(let value):
            try container.encode(value, forKey: .infoType)
          case .customTag(let value):
            try container.encode(value, forKey: .customTag)
          case .inferred(let value):
            try container.encode(value, forKey: .inferred)
          }
        }
      }

      /// Semantic tag that identifies what a column contains, to determine which
      /// statistical model to use to estimate the reidentifiability of each
      /// value. [required]
      public enum OneOf_Tag: Codable, Equatable, Sendable {
        /// A column can be tagged with a InfoType to use the relevant public
        /// dataset as a statistical model of population, if available. We
        /// currently support US ZIP codes, region codes, ages and genders.
        /// To programmatically obtain the list of supported InfoTypes, use
        /// ListInfoTypes with the supported_by=RISK_ANALYSIS filter.
        indirect case infoType(InfoType?)
        /// A column can be tagged with a custom tag. In this case, the user must
        /// indicate an auxiliary table that contains statistical information on
        /// the possible values of this column.
        case customTag(Swift.String)
        /// If no semantic tag is indicated, we infer the statistical model from
        /// the distribution of values in the input data
        indirect case inferred(GoogleCloudWkt.Empty?)
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.TaggedField"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// An auxiliary table contains statistical information on the relative
    /// frequency of different quasi-identifiers values. It has one or several
    /// quasi-identifiers columns, and one column that indicates the relative
    /// frequency of each quasi-identifier tuple.
    /// If a tuple is present in the data but not in the auxiliary table, the
    /// corresponding relative frequency is assumed to be zero (and thus, the
    /// tuple is highly reidentifiable).
    public struct AuxiliaryTable: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Required. Auxiliary table location.
      public var table: BigQueryTable? = nil

      /// Required. Quasi-identifier columns.
      public var quasiIds: [PrivacyMetric.KMapEstimationConfig.AuxiliaryTable.QuasiIdField] = []

      /// Required. The relative frequency column must contain a floating-point
      /// number between 0 and 1 (inclusive). Null values are assumed to be zero.
      public var relativeFrequency: FieldId? = nil

      /// Initialize a new instance of `AuxiliaryTable`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = AuxiliaryTable().with { $0.table = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      /// A quasi-identifier column has a custom_tag, used to know which column
      /// in the data corresponds to which column in the statistical model.
      public struct QuasiIdField: Codable, Equatable, GoogleCloudWkt._AnyPackable,
        Sendable
      {
        /// Identifies the column.
        public var field: FieldId? = nil

        /// A auxiliary field.
        public var customTag: Swift.String = Swift.String()

        /// Initialize a new instance of `QuasiIdField`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = QuasiIdField().with { $0.field = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        public static var _anyTypeUrl: Swift.String {
          return
            "type.googleapis.com/google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.AuxiliaryTable.QuasiIdField"
        }
        public init(fromAny any: GoogleCloudWkt.`Any`) throws {
          self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWkt.Struct {
          return try GoogleCloudWkt._slowAnySerialize(message: self)
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig.AuxiliaryTable"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.PrivacyMetric.KMapEstimationConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// δ-presence metric, used to estimate how likely it is for an attacker to
  /// figure out that one given individual appears in a de-identified dataset.
  /// Similarly to the k-map metric, we cannot compute δ-presence exactly without
  /// knowing the attack dataset, so we use a statistical model instead.
  public struct DeltaPresenceEstimationConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. Fields considered to be quasi-identifiers. No two fields can
    /// have the same tag.
    public var quasiIds: [QuasiId] = []

    /// ISO 3166-1 alpha-2 region code to use in the statistical modeling.
    /// Set if no column is tagged with a region-specific InfoType (like
    /// US_ZIP_5) or a region code.
    public var regionCode: Swift.String = Swift.String()

    /// Several auxiliary tables can be used in the analysis. Each custom_tag
    /// used to tag a quasi-identifiers field must appear in exactly one
    /// field of one auxiliary table.
    public var auxiliaryTables: [StatisticalTable] = []

    /// Initialize a new instance of `DeltaPresenceEstimationConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DeltaPresenceEstimationConfig().with { $0.quasiIds = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.privacy.dlp.v2.PrivacyMetric.DeltaPresenceEstimationConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Types of analysis.
  public enum OneOf_Type_: Codable, Equatable, Sendable {
    /// Numerical stats
    indirect case numericalStatsConfig(PrivacyMetric.NumericalStatsConfig?)
    /// Categorical stats
    indirect case categoricalStatsConfig(PrivacyMetric.CategoricalStatsConfig?)
    /// K-anonymity
    indirect case kAnonymityConfig(PrivacyMetric.KAnonymityConfig?)
    /// l-diversity
    indirect case lDiversityConfig(PrivacyMetric.LDiversityConfig?)
    /// k-map
    indirect case kMapEstimationConfig(PrivacyMetric.KMapEstimationConfig?)
    /// delta-presence
    indirect case deltaPresenceEstimationConfig(PrivacyMetric.DeltaPresenceEstimationConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.PrivacyMetric"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
