// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Discovery target for credentials and secrets in cloud resource metadata.
///
/// This target does not include any filtering or frequency controls. Cloud
/// DLP will scan cloud resource metadata for secrets daily.
///
/// No inspect template should be included in the discovery config for a
/// security benchmarks scan. Instead, the built-in list of secrets and
/// credentials infoTypes will be used (see
/// https://cloud.google.com/sensitive-data-protection/docs/infotypes-reference#credentials_and_secrets).
///
/// Credentials and secrets discovered will be reported as vulnerabilities to
/// Security Command Center.
public struct SecretsDiscoveryTarget: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Initialize a new instance of `SecretsDiscoveryTarget`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SecretsDiscoveryTarget().with { $0.<placeholder> = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.privacy.dlp.v2.SecretsDiscoveryTarget"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
