// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Version of a StoredInfoType, including the configuration used to build it,
/// create timestamp, and current state.
public struct StoredInfoTypeVersion: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// StoredInfoType configuration.
  public var config: StoredInfoTypeConfig? = nil

  /// Create timestamp of the version. Read-only, determined by the system
  /// when the version is created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Stored info type version state. Read-only, updated by the system
  /// during dictionary creation.
  public var state: StoredInfoTypeState = StoredInfoTypeState()

  /// Errors that occurred when creating this storedInfoType version, or
  /// anomalies detected in the storedInfoType data that render it unusable. Only
  /// the five most recent errors will be displayed, with the most recent error
  /// appearing first.
  ///
  /// For example, some of the data for stored custom dictionaries is put in
  /// the user's Cloud Storage bucket, and if this data is modified or
  /// deleted by the user or another system, the dictionary becomes invalid.
  ///
  /// If any errors occur, fix the problem indicated by the error message and
  /// use the UpdateStoredInfoType API method to create another version of the
  /// storedInfoType to continue using it, reusing the same `config` if it was
  /// not the source of the error.
  public var errors: [Error] = []

  /// Statistics about this storedInfoType version.
  public var stats: StoredInfoTypeStats? = nil

  /// Initialize a new instance of `StoredInfoTypeVersion`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StoredInfoTypeVersion().with { $0.config = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.privacy.dlp.v2.StoredInfoTypeVersion"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
