// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// User specified templates and configs for how to deidentify structured,
/// unstructures, and image files. User must provide either a unstructured
/// deidentify template or at least one redact image config.
public struct TransformationConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// De-identify template.
  /// If this template is specified, it will serve as the default de-identify
  /// template. This template cannot contain `record_transformations` since it
  /// can be used for unstructured content such as free-form text files. If this
  /// template is not set, a default `ReplaceWithInfoTypeConfig` will be used to
  /// de-identify unstructured content.
  public var deidentifyTemplate: Swift.String = Swift.String()

  /// Structured de-identify template.
  /// If this template is specified, it will serve as the de-identify template
  /// for structured content such as delimited files and tables. If this template
  /// is not set but the `deidentify_template` is set, then `deidentify_template`
  /// will also apply to the structured content. If neither template is set, a
  /// default `ReplaceWithInfoTypeConfig` will be used to de-identify structured
  /// content.
  public var structuredDeidentifyTemplate: Swift.String = Swift.String()

  /// Image redact template.
  /// If this template is specified, it will serve as the de-identify template
  /// for images. If this template is not set, all findings in the image will be
  /// redacted with a black box.
  public var imageRedactTemplate: Swift.String = Swift.String()

  /// Initialize a new instance of `TransformationConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TransformationConfig().with { $0.deidentifyTemplate = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.privacy.dlp.v2.TransformationConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
