// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Match dataset resources using regex filters.
public struct VertexDatasetCollection: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The pattern used to filter dataset resources.
  public var pattern: OneOf_Pattern? = nil

  /// Initialize a new instance of `VertexDatasetCollection`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VertexDatasetCollection().with { $0.vertexDatasetRegexes = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: String, CodingKey {
    case vertexDatasetRegexes = "vertexDatasetRegexes"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var pattern: OneOf_Pattern? = nil
    let patternCheckAndSet = {
      if pattern != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'pattern'"))
      }
      pattern = $0
    }
    if let vertexDatasetRegexes = try container.decodeIfPresent(
      VertexDatasetRegexes?.self, forKey: .vertexDatasetRegexes)
    {
      try patternCheckAndSet(.vertexDatasetRegexes(vertexDatasetRegexes))
    }
    self.pattern = pattern
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.pattern {
      switch choice {
      case .vertexDatasetRegexes(let value):
        try container.encode(value, forKey: .vertexDatasetRegexes)
      }
    }
  }

  /// The pattern used to filter dataset resources.
  public enum OneOf_Pattern: Codable, Equatable, Sendable {
    /// The regex used to filter dataset resources.
    indirect case vertexDatasetRegexes(VertexDatasetRegexes?)
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.privacy.dlp.v2.VertexDatasetCollection"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
